/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupInterface.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupInterface.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;

import com.splwg.base.api.datatypes.LookupHelper;

/**
 * AccessModeLookup is a class that represents the lookup field ACCESS_MODE
 * and its values:
   <table>
     <tr> <th>FIELD_VALUE</th> <th>Property Name</th> <th>Description</th> </tr>
     <tr> <td>CMAX</td> <td>awaitingCancelation</td>
             <td>Awaiting Cancelation</td> </tr>
     <tr> <td>MASK</td> <td>cmMask</td>
             <td>MASK</td> </tr>
     <tr> <td>SHOW</td> <td>cmShow</td>
             <td>Show</td> </tr>
    </table>
 * stored on the tables CI_LOOKUP_FIELD, CI_LOOKUP_VALUE.
 *
 * @author Generated by splDev.artifactGenerator
 */
public interface AccessModeLookup extends com.splwg.ccb.api.lookup.AccessModeLookup {

    //~ Static fields/initializers ---------------------------------------------------------------------------

    /* constants */
    public static final Constants constants = new Constants();
    
    public static class Constants {
        // New values
        /** Constant value representing lookup value for awaitingCancelation (value = 'CMAX')*/
        public AccessModeLookup AWAITING_CANCELATION; 
        /** Constant value representing lookup value for cmMask (value = 'MASK')*/
        public AccessModeLookup CM_MASK; 
        /** Constant value representing lookup value for cmShow (value = 'SHOW')*/
        public AccessModeLookup CM_SHOW; 
        // Old Values
        /** Constant value representing lookup value for acceptProposalSa (value = 'APSA')*/
        public AccessModeLookup ACCEPT_PROPOSAL_SA; 
        /** Constant value representing lookup value for displayQuote (value = 'DQTE')*/
        public AccessModeLookup DISPLAY_QUOTE; 
        /** Constant value representing lookup value for forward (value = 'FWRD')*/
        public AccessModeLookup FORWARD; 
        /** Constant value representing lookup value for pendingState (value = 'C1PE')*/
        public AccessModeLookup PENDING_STATE; 
        /** Constant value representing lookup value for processed (value = 'C1PC')*/
        public AccessModeLookup PROCESSED; 
        /** Constant value representing lookup value for error1 (value = 'E   ')*/
        public AccessModeLookup ERROR_1; 
        /** Constant value representing lookup value for queue (value = 'QB  ')*/
        public AccessModeLookup QUEUE; 
        /** Constant value representing lookup value for showAppointment (value = 'SAPT')*/
        public AccessModeLookup SHOW_APPOINTMENT; 
        /** Constant value representing lookup value for notifyingCustomer (value = 'F1NR')*/
        public AccessModeLookup NOTIFYING_CUSTOMER; 
        /** Constant value representing lookup value for creditNote (value = 'CR  ')*/
        public AccessModeLookup CREDIT_NOTE; 
        /** Constant value representing lookup value for enable (value = 'ENBL')*/
        public AccessModeLookup ENABLE; 
        /** Constant value representing lookup value for writeOff (value = 'WO  ')*/
        public AccessModeLookup WRITE_OFF; 
        /** Constant value representing lookup value for waiting (value = 'C1WT')*/
        public AccessModeLookup WAITING; 
        /** Constant value representing lookup value for forceCheckIn (value = 'F1FC')*/
        public AccessModeLookup FORCE_CHECK_IN; 
        /** Constant value representing lookup value for cancel (value = 'CA  ')*/
        public AccessModeLookup CANCEL; 
        /** Constant value representing lookup value for rereadMeter (value = 'RERD')*/
        public AccessModeLookup REREAD_METER; 
        /** Constant value representing lookup value for deleteQuoteDetail (value = 'DQDT')*/
        public AccessModeLookup DELETE_QUOTE_DETAIL; 
        /** Constant value representing lookup value for addSaRelationship (value = 'ASAR')*/
        public AccessModeLookup ADD_SA_RELATIONSHIP; 
        /** Constant value representing lookup value for activateProposalSa (value = 'QPSA')*/
        public AccessModeLookup ACTIVATE_PROPOSAL_SA; 
        /** Constant value representing lookup value for tenderCancel (value = 'TC  ')*/
        public AccessModeLookup TENDER_CANCEL; 
        /** Constant value representing lookup value for bundle (value = 'BNDL')*/
        public AccessModeLookup BUNDLE; 
        /** Constant value representing lookup value for generateQuote (value = 'GQTE')*/
        public AccessModeLookup GENERATE_QUOTE; 
        /** Constant value representing lookup value for declineProposalSa (value = 'DPSA')*/
        public AccessModeLookup DECLINE_PROPOSAL_SA; 
        /** Constant value representing lookup value for issue (value = 'ISS ')*/
        public AccessModeLookup ISSUE; 
        /** Constant value representing lookup value for matchEventFtLinkUnlink (value = 'FTLU')*/
        public AccessModeLookup MATCH_EVENT_FT_LINK_UNLINK; 
        /** Constant value representing lookup value for postProcess (value = 'C1PP')*/
        public AccessModeLookup POST_PROCESS; 
        /** Constant value representing lookup value for displayStatement (value = 'DS  ')*/
        public AccessModeLookup DISPLAY_STATEMENT; 
        /** Constant value representing lookup value for pending (value = 'PE  ')*/
        public AccessModeLookup PENDING; 
        /** Constant value representing lookup value for reverseWriteOff (value = 'RWO ')*/
        public AccessModeLookup REVERSE_WRITE_OFF; 
        /** Constant value representing lookup value for applyNewStartOption (value = 'APST')*/
        public AccessModeLookup APPLY_NEW_START_OPTION; 
        /** Constant value representing lookup value for timedOut (value = 'TO  ')*/
        public AccessModeLookup TIMED_OUT; 
        /** Constant value representing lookup value for billDeterminantsReceived (value = 'BDR ')*/
        public AccessModeLookup BILL_DETERMINANTS_RECEIVED; 
        /** Constant value representing lookup value for inProgress (value = 'C1PR')*/
        public AccessModeLookup IN_PROGRESS; 
        /** Constant value representing lookup value for awaitingCustomerResponse (value = 'F1OK')*/
        public AccessModeLookup AWAITING_CUSTOMER_RESPONSE; 
        /** Constant value representing lookup value for processMessage (value = 'PM  ')*/
        public AccessModeLookup PROCESS_MESSAGE; 
        /** Constant value representing lookup value for reprint (value = 'RP  ')*/
        public AccessModeLookup REPRINT; 
        /** Constant value representing lookup value for reverseTrueUp (value = 'RTRU')*/
        public AccessModeLookup REVERSE_TRUE_UP; 
        /** Constant value representing lookup value for apply (value = 'APLY')*/
        public AccessModeLookup APPLY; 
        /** Constant value representing lookup value for displayBill (value = 'DB  ')*/
        public AccessModeLookup DISPLAY_BILL; 
        /** Constant value representing lookup value for cancelBill (value = 'CAB ')*/
        public AccessModeLookup CANCEL_BILL; 
        /** Constant value representing lookup value for change (value = 'C   ')*/
        public AccessModeLookup CHANGE; 
        /** Constant value representing lookup value for approvedState (value = 'C1AP')*/
        public AccessModeLookup APPROVED_STATE; 
        /** Constant value representing lookup value for displayFieldOrder (value = 'DF  ')*/
        public AccessModeLookup DISPLAY_FIELD_ORDER; 
        /** Constant value representing lookup value for updateMaxAppointments (value = 'UPAP')*/
        public AccessModeLookup UPDATE_MAX_APPOINTMENTS; 
        /** Constant value representing lookup value for accumulateStatistics (value = 'C1AS')*/
        public AccessModeLookup ACCUMULATE_STATISTICS; 
        /** Constant value representing lookup value for accepted (value = 'C1AT')*/
        public AccessModeLookup ACCEPTED; 
        /** Constant value representing lookup value for preProcess (value = 'C1RE')*/
        public AccessModeLookup PRE_PROCESS; 
        /** Constant value representing lookup value for initiateStopSa (value = 'ISSA')*/
        public AccessModeLookup INITIATE_STOP_SA; 
        /** Constant value representing lookup value for reactivateProposalSa (value = 'RPSA')*/
        public AccessModeLookup REACTIVATE_PROPOSAL_SA; 
        /** Constant value representing lookup value for generateQuoteDetail (value = 'GQDT')*/
        public AccessModeLookup GENERATE_QUOTE_DETAIL; 
        /** Constant value representing lookup value for approvalInProgressState (value = 'C1IP')*/
        public AccessModeLookup APPROVAL_IN_PROGRESS_STATE; 
        /** Constant value representing lookup value for failDeviceTest (value = 'FA  ')*/
        public AccessModeLookup FAIL_DEVICE_TEST; 
        /** Constant value representing lookup value for invalid (value = 'C1IV')*/
        public AccessModeLookup INVALID; 
        /** Constant value representing lookup value for initiated (value = 'C1IT')*/
        public AccessModeLookup INITIATED; 
        /** Constant value representing lookup value for inactiveState (value = 'C1IN')*/
        public AccessModeLookup INACTIVE_STATE; 
        /** Constant value representing lookup value for activeState (value = 'C1AC')*/
        public AccessModeLookup ACTIVE_STATE; 
        /** Constant value representing lookup value for allPaymentFreeze (value = 'AF  ')*/
        public AccessModeLookup ALL_PAYMENT_FREEZE; 
        /** Constant value representing lookup value for startServiceonPremises (value = 'PMSS')*/
        public AccessModeLookup START_SERVICEON_PREMISES; 
        /** Constant value representing lookup value for stopServiceonPremises (value = 'PMST')*/
        public AccessModeLookup STOP_SERVICEON_PREMISES; 
        /** Constant value representing lookup value for saveAndShowPackages (value = 'SP  ')*/
        public AccessModeLookup SAVE_AND_SHOW_PACKAGES; 
        /** Constant value representing lookup value for incomplete (value = 'C1IC')*/
        public AccessModeLookup INCOMPLETE; 
        /** Constant value representing lookup value for issueDetectedState (value = 'C1ID')*/
        public AccessModeLookup ISSUE_DETECTED_STATE; 
        /** Constant value representing lookup value for stop (value = 'ST  ')*/
        public AccessModeLookup STOP; 
        /** Constant value representing lookup value for sync (value = 'SY  ')*/
        public AccessModeLookup SYNC; 
        /** Constant value representing lookup value for deleteSequence (value = 'C1SD')*/
        public AccessModeLookup DELETE_SEQUENCE; 
        /** Constant value representing lookup value for matchEventLinkUnlink (value = 'MELU')*/
        public AccessModeLookup MATCH_EVENT_LINK_UNLINK; 
        /** Constant value representing lookup value for getNextNumber (value = 'C1SG')*/
        public AccessModeLookup GET_NEXT_NUMBER; 
        /** Constant value representing lookup value for assignLandlord (value = 'PMAL')*/
        public AccessModeLookup ASSIGN_LANDLORD; 
        /** Constant value representing lookup value for validateDeviceTest (value = 'VA  ')*/
        public AccessModeLookup VALIDATE_DEVICE_TEST; 
        /** Constant value representing lookup value for supervisorAssignment (value = 'ASSV')*/
        public AccessModeLookup SUPERVISOR_ASSIGNMENT; 
        /** Constant value representing lookup value for assignParentPremise (value = 'PMAP')*/
        public AccessModeLookup ASSIGN_PARENT_PREMISE; 
        /** Constant value representing lookup value for submitForApproval (value = 'S   ')*/
        public AccessModeLookup SUBMIT_FOR_APPROVAL; 
        /** Constant value representing lookup value for freeze (value = 'F   ')*/
        public AccessModeLookup FREEZE; 
        /** Constant value representing lookup value for reopenQuote (value = 'RQTE')*/
        public AccessModeLookup REOPEN_QUOTE; 
        /** Constant value representing lookup value for paymentDistribute (value = 'PD  ')*/
        public AccessModeLookup PAYMENT_DISTRIBUTE; 
        /** Constant value representing lookup value for resent (value = 'C1RS')*/
        public AccessModeLookup RESENT; 
        /** Constant value representing lookup value for active (value = 'F1AC')*/
        public AccessModeLookup ACTIVE; 
        /** Constant value representing lookup value for sendBack (value = 'SBCK')*/
        public AccessModeLookup SEND_BACK; 
        /** Constant value representing lookup value for awaitingProcess (value = 'C1RQ')*/
        public AccessModeLookup AWAITING_PROCESS; 
        /** Constant value representing lookup value for removeLandlord (value = 'PMRL')*/
        public AccessModeLookup REMOVE_LANDLORD; 
        /** Constant value representing lookup value for receiptVerificationState (value = 'C1RV')*/
        public AccessModeLookup RECEIPT_VERIFICATION_STATE; 
        /** Constant value representing lookup value for inactive (value = 'F1IN')*/
        public AccessModeLookup INACTIVE; 
        /** Constant value representing lookup value for removeParentPremise (value = 'PMRP')*/
        public AccessModeLookup REMOVE_PARENT_PREMISE; 
        /** Constant value representing lookup value for rejectedState (value = 'C1RJ')*/
        public AccessModeLookup REJECTED_STATE; 
        /** Constant value representing lookup value for reopen (value = 'RO  ')*/
        public AccessModeLookup REOPEN; 
        /** Constant value representing lookup value for transfer (value = 'TR  ')*/
        public AccessModeLookup TRANSFER; 
        /** Constant value representing lookup value for cancelSelected (value = 'CNSL')*/
        public AccessModeLookup CANCEL_SELECTED; 
        /** Constant value representing lookup value for assign (value = 'ASSG')*/
        public AccessModeLookup ASSIGN; 
        /** Constant value representing lookup value for awaitingAcknowledgement (value = 'F1AA')*/
        public AccessModeLookup AWAITING_ACKNOWLEDGEMENT; 
        /** Constant value representing lookup value for reinstateSa (value = 'RSA ')*/
        public AccessModeLookup REINSTATE_SA; 
        /** Constant value representing lookup value for inactivate (value = 'INAC')*/
        public AccessModeLookup INACTIVATE; 
        /** Constant value representing lookup value for break (value = 'BK  ')*/
        public AccessModeLookup BREAK; 
        /** Constant value representing lookup value for awaitingBillDeterminant (value = 'ABD ')*/
        public AccessModeLookup AWAITING_BILL_DETERMINANT; 
        /** Constant value representing lookup value for terminated (value = 'C1TE')*/
        public AccessModeLookup TERMINATED; 
        /** Constant value representing lookup value for revert (value = 'RV  ')*/
        public AccessModeLookup REVERT; 
        /** Constant value representing lookup value for add (value = 'A   ')*/
        public AccessModeLookup ADD; 
        /** Constant value representing lookup value for correctionNote (value = 'C1CO')*/
        public AccessModeLookup CORRECTION_NOTE; 
        /** Constant value representing lookup value for stopAutopay (value = 'STAP')*/
        public AccessModeLookup STOP_AUTOPAY; 
        /** Constant value representing lookup value for confirmManualAmounts (value = 'C1CN')*/
        public AccessModeLookup CONFIRM_MANUAL_AMOUNTS; 
        /** Constant value representing lookup value for setSequenceNumber (value = 'C1SS')*/
        public AccessModeLookup SET_SEQUENCE_NUMBER; 
        /** Constant value representing lookup value for reopenToDo (value = 'REOP')*/
        public AccessModeLookup REOPEN_TO_DO; 
        /** Constant value representing lookup value for calculatingBillSegment (value = 'C1CB')*/
        public AccessModeLookup CALCULATING_BILL_SEGMENT; 
        /** Constant value representing lookup value for restoreRevision (value = 'F1RS')*/
        public AccessModeLookup RESTORE_REVISION; 
        /** Constant value representing lookup value for success (value = 'C1SU')*/
        public AccessModeLookup SUCCESS; 
        /** Constant value representing lookup value for undo (value = 'UN  ')*/
        public AccessModeLookup UNDO; 
        /** Constant value representing lookup value for create (value = 'CRE ')*/
        public AccessModeLookup CREATE; 
        /** Constant value representing lookup value for start (value = 'STRT')*/
        public AccessModeLookup START; 
        /** Constant value representing lookup value for close (value = 'CL  ')*/
        public AccessModeLookup CLOSE; 
        /** Constant value representing lookup value for snapshot (value = 'C1SN')*/
        public AccessModeLookup SNAPSHOT; 
        /** Constant value representing lookup value for determineIfTopUpNeeded (value = 'C1DT')*/
        public AccessModeLookup DETERMINE_IF_TOP_UP_NEEDED; 
        /** Constant value representing lookup value for closeQuote (value = 'CQTE')*/
        public AccessModeLookup CLOSE_QUOTE; 
        /** Constant value representing lookup value for copyAppointments (value = 'CPAP')*/
        public AccessModeLookup COPY_APPOINTMENTS; 
        /** Constant value representing lookup value for undoCorrectionNote (value = 'C1UC')*/
        public AccessModeLookup UNDO_CORRECTION_NOTE; 
        /** Constant value representing lookup value for delete (value = 'D   ')*/
        public AccessModeLookup DELETE; 
        /** Constant value representing lookup value for cancelQuote (value = 'XQTE')*/
        public AccessModeLookup CANCEL_QUOTE; 
        /** Constant value representing lookup value for allPaymentDistribute (value = 'AD  ')*/
        public AccessModeLookup ALL_PAYMENT_DISTRIBUTE; 
        /** Constant value representing lookup value for remove (value = 'RMVE')*/
        public AccessModeLookup REMOVE; 
        /** Constant value representing lookup value for derive (value = 'ID  ')*/
        public AccessModeLookup DERIVE; 
        /** Constant value representing lookup value for rebill (value = 'RB  ')*/
        public AccessModeLookup REBILL; 
        /** Constant value representing lookup value for paymentCancel (value = 'PC  ')*/
        public AccessModeLookup PAYMENT_CANCEL; 
        /** Constant value representing lookup value for superUser (value = 'F1SU')*/
        public AccessModeLookup SUPER_USER; 
        /** Constant value representing lookup value for linked (value = 'C1LK')*/
        public AccessModeLookup LINKED; 
        /** Constant value representing lookup value for updateSelected (value = 'UPSL')*/
        public AccessModeLookup UPDATE_SELECTED; 
        /** Constant value representing lookup value for synchronized (value = 'F1SY')*/
        public AccessModeLookup SYNCHRONIZED; 
        /** Constant value representing lookup value for transferStockLocationItem (value = 'TSLI')*/
        public AccessModeLookup TRANSFER_STOCK_LOCATION_ITEM; 
        /** Constant value representing lookup value for determineApprovers (value = 'C1DA')*/
        public AccessModeLookup DETERMINE_APPROVERS; 
        /** Constant value representing lookup value for sendReq (value = 'F1SR')*/
        public AccessModeLookup SEND_REQ; 
        /** Constant value representing lookup value for hold (value = 'HO  ')*/
        public AccessModeLookup HOLD; 
        /** Constant value representing lookup value for transferStockLocationMeter (value = 'TSLM')*/
        public AccessModeLookup TRANSFER_STOCK_LOCATION_METER; 
        /** Constant value representing lookup value for cancelRebillFreeze (value = 'CRF ')*/
        public AccessModeLookup CANCEL_REBILL_FREEZE; 
        /** Constant value representing lookup value for migrationApproved (value = 'F1MA')*/
        public AccessModeLookup MIGRATION_APPROVED; 
        /** Constant value representing lookup value for validateState (value = 'C1VD')*/
        public AccessModeLookup VALIDATE_STATE; 
        /** Constant value representing lookup value for freezeComplete (value = 'FC  ')*/
        public AccessModeLookup FREEZE_COMPLETE; 
        /** Constant value representing lookup value for verificationState (value = 'C1VE')*/
        public AccessModeLookup VERIFICATION_STATE; 
        /** Constant value representing lookup value for completeQuote (value = 'FQTE')*/
        public AccessModeLookup COMPLETE_QUOTE; 
        /** Constant value representing lookup value for migrationCancelApply (value = 'F1MC')*/
        public AccessModeLookup MIGRATION_CANCEL_APPLY; 
        /** Constant value representing lookup value for sendRequest (value = 'SRQ ')*/
        public AccessModeLookup SEND_REQUEST; 
        /** Constant value representing lookup value for messageSent (value = 'C1MS')*/
        public AccessModeLookup MESSAGE_SENT; 
        /** Constant value representing lookup value for displayLetter (value = 'LD  ')*/
        public AccessModeLookup DISPLAY_LETTER; 
        /** Constant value representing lookup value for inquire (value = 'R   ')*/
        public AccessModeLookup INQUIRE; 
        /** Constant value representing lookup value for transferDistributionRule (value = 'TRDR')*/
        public AccessModeLookup TRANSFER_DISTRIBUTION_RULE; 
        /** Constant value representing lookup value for cancelProposalSa (value = 'CPSA')*/
        public AccessModeLookup CANCEL_PROPOSAL_SA; 
        /** Constant value representing lookup value for processingError (value = 'C1ER')*/
        public AccessModeLookup PROCESSING_ERROR; 
        /** Constant value representing lookup value for determineSyncNeeded (value = 'F1DS')*/
        public AccessModeLookup DETERMINE_SYNC_NEEDED; 
        /** Constant value representing lookup value for generate (value = 'G   ')*/
        public AccessModeLookup GENERATE; 
        /** Constant value representing lookup value for complete (value = 'CO  ')*/
        public AccessModeLookup COMPLETE; 
        /** Constant value representing lookup value for deleteEntity (value = 'F1DE')*/
        public AccessModeLookup DELETE_ENTITY; 
        /** Constant value representing lookup value for cancelled (value = 'CAN ')*/
        public AccessModeLookup CANCELLED; 
        /** Constant value representing lookup value for createSubSa (value = 'CS  ')*/
        public AccessModeLookup CREATE_SUB_SA; 
        /** Constant value representing lookup value for trueUp (value = 'TRUP')*/
        public AccessModeLookup TRUE_UP; 
        /** Constant value representing lookup value for discard (value = 'F1DC')*/
        public AccessModeLookup DISCARD; 
        /** Constant value representing lookup value for submitViewReport (value = 'SV  ')*/
        public AccessModeLookup SUBMIT_VIEW_REPORT; 
        /** Constant value representing lookup value for callback (value = 'CK  ')*/
        public AccessModeLookup CALLBACK; 
        /** Constant value representing lookup value for execute (value = 'F1EX')*/
        public AccessModeLookup EXECUTE; 
        /** Constant value representing lookup value for getNextToDoAssignedToYou (value = 'F1NA')*/
        public AccessModeLookup GET_NEXT_TO_DO_ASSIGNED_TO_YOU; 
        /** Constant value representing lookup value for triggerEvents (value = 'TGEV')*/
        public AccessModeLookup TRIGGER_EVENTS; 
        /** Constant value representing lookup value for cancelFrozen (value = 'CF  ')*/
        public AccessModeLookup CANCEL_FROZEN; 
        /** Constant value representing lookup value for activate (value = 'AC  ')*/
        public AccessModeLookup ACTIVATE; 
        /** Constant value representing lookup value for objected (value = 'C1OB')*/
        public AccessModeLookup OBJECTED; 
        /** Constant value representing lookup value for initiateCancel (value = 'IC  ')*/
        public AccessModeLookup INITIATE_CANCEL; 
        /** Constant value representing lookup value for expireServiceAgreementRelationship (value = 'XSAR')*/
        public AccessModeLookup EXPIRE_SERVICE_AGREEMENT_RELATIONSHIP; 
        /** Constant value representing lookup value for captureFinalSnapshot (value = 'C1FS')*/
        public AccessModeLookup CAPTURE_FINAL_SNAPSHOT; 
        /** Constant value representing lookup value for withdraw (value = 'C1WD')*/
        public AccessModeLookup WITHDRAW; 
        /** Constant value representing lookup value for touDerive (value = 'TD  ')*/
        public AccessModeLookup TOU_DERIVE; 
        /** Constant value representing lookup value for syncError (value = 'F1ER')*/
        public AccessModeLookup SYNC_ERROR; 
        /** Constant value representing lookup value for cancelEvent (value = 'CAEV')*/
        public AccessModeLookup CANCEL_EVENT; 
        /** Constant value representing lookup value for noApprovalNecessary (value = 'C1NO')*/
        public AccessModeLookup NO_APPROVAL_NECESSARY; 
        /** Constant value representing lookup value for paymentFreeze (value = 'PF  ')*/
        public AccessModeLookup PAYMENT_FREEZE; 
        /** Constant value representing lookup value for migrationNeedsReview (value = 'F1MN')*/
        public AccessModeLookup MIGRATION_NEEDS_REVIEW; 
        /** Constant value representing lookup value for billDeterminantsProcessed (value = 'BDP ')*/
        public AccessModeLookup BILL_DETERMINANTS_PROCESSED; 
        /** Constant value representing lookup value for noResponse (value = 'C1NR')*/
        public AccessModeLookup NO_RESPONSE; 
        /** Constant value representing lookup value for awaitingDataSync (value = 'ADS ')*/
        public AccessModeLookup AWAITING_DATA_SYNC; 
        /** Constant value representing lookup value for noProcessingRequired (value = 'C1NP')*/
        public AccessModeLookup NO_PROCESSING_REQUIRED; 
        /** Constant value representing lookup value for validationErrorState (value = 'C1VX')*/
        public AccessModeLookup VALIDATION_ERROR_STATE; 
        /** Constant value representing lookup value for migrationRejected (value = 'F1MR')*/
        public AccessModeLookup MIGRATION_REJECTED; 
        /** Constant value representing lookup value for migrationCannotApply (value = 'F1MI')*/
        public AccessModeLookup MIGRATION_CANNOT_APPLY; 
        /** Constant value representing lookup value for other (value = 'OTH ')*/
        public AccessModeLookup OTHER; 
        /** Constant value representing lookup value for validated (value = 'C1VL')*/
        public AccessModeLookup VALIDATED; 
        /** Constant value representing lookup value for paymentDelete (value = 'DL  ')*/
        public AccessModeLookup PAYMENT_DELETE; 

        public void initialize() {
            // new values
            AWAITING_CANCELATION = 
                LookupHelper.getLookupInstance(AccessModeLookup.class, "CMAX");

            CM_MASK = 
                LookupHelper.getLookupInstance(AccessModeLookup.class, "MASK");

            CM_SHOW = 
                LookupHelper.getLookupInstance(AccessModeLookup.class, "SHOW");

           // original values
             ACCEPT_PROPOSAL_SA = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.ACCEPT_PROPOSAL_SA;
             DISPLAY_QUOTE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.DISPLAY_QUOTE;
             FORWARD = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.FORWARD;
             PENDING_STATE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.PENDING_STATE;
             PROCESSED = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.PROCESSED;
             ERROR_1 = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.ERROR_1;
             QUEUE = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.QUEUE;
             SHOW_APPOINTMENT = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.SHOW_APPOINTMENT;
             NOTIFYING_CUSTOMER = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.NOTIFYING_CUSTOMER;
             CREDIT_NOTE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.CREDIT_NOTE;
             ENABLE = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.ENABLE;
             WRITE_OFF = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.WRITE_OFF;
             WAITING = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.WAITING;
             FORCE_CHECK_IN = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.FORCE_CHECK_IN;
             CANCEL = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.CANCEL;
             REREAD_METER = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.REREAD_METER;
             DELETE_QUOTE_DETAIL = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.DELETE_QUOTE_DETAIL;
             ADD_SA_RELATIONSHIP = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.ADD_SA_RELATIONSHIP;
             ACTIVATE_PROPOSAL_SA = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.ACTIVATE_PROPOSAL_SA;
             TENDER_CANCEL = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.TENDER_CANCEL;
             BUNDLE = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.BUNDLE;
             GENERATE_QUOTE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.GENERATE_QUOTE;
             DECLINE_PROPOSAL_SA = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.DECLINE_PROPOSAL_SA;
             ISSUE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.ISSUE;
             MATCH_EVENT_FT_LINK_UNLINK = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.MATCH_EVENT_FT_LINK_UNLINK;
             POST_PROCESS = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.POST_PROCESS;
             DISPLAY_STATEMENT = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.DISPLAY_STATEMENT;
             PENDING = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.PENDING;
             REVERSE_WRITE_OFF = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.REVERSE_WRITE_OFF;
             APPLY_NEW_START_OPTION = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.APPLY_NEW_START_OPTION;
             TIMED_OUT = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.TIMED_OUT;
             BILL_DETERMINANTS_RECEIVED = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.BILL_DETERMINANTS_RECEIVED;
             IN_PROGRESS = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.IN_PROGRESS;
             AWAITING_CUSTOMER_RESPONSE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.AWAITING_CUSTOMER_RESPONSE;
             PROCESS_MESSAGE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.PROCESS_MESSAGE;
             REPRINT = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.REPRINT;
             REVERSE_TRUE_UP = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.REVERSE_TRUE_UP;
             APPLY = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.APPLY;
             DISPLAY_BILL = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.DISPLAY_BILL;
             CANCEL_BILL = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.CANCEL_BILL;
             CHANGE = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.CHANGE;
             APPROVED_STATE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.APPROVED_STATE;
             DISPLAY_FIELD_ORDER = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.DISPLAY_FIELD_ORDER;
             UPDATE_MAX_APPOINTMENTS = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.UPDATE_MAX_APPOINTMENTS;
             ACCUMULATE_STATISTICS = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.ACCUMULATE_STATISTICS;
             ACCEPTED = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.ACCEPTED;
             PRE_PROCESS = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.PRE_PROCESS;
             INITIATE_STOP_SA = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.INITIATE_STOP_SA;
             REACTIVATE_PROPOSAL_SA = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.REACTIVATE_PROPOSAL_SA;
             GENERATE_QUOTE_DETAIL = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.GENERATE_QUOTE_DETAIL;
             APPROVAL_IN_PROGRESS_STATE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.APPROVAL_IN_PROGRESS_STATE;
             FAIL_DEVICE_TEST = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.FAIL_DEVICE_TEST;
             INVALID = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.INVALID;
             INITIATED = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.INITIATED;
             INACTIVE_STATE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.INACTIVE_STATE;
             ACTIVE_STATE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.ACTIVE_STATE;
             ALL_PAYMENT_FREEZE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.ALL_PAYMENT_FREEZE;
             START_SERVICEON_PREMISES = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.START_SERVICEON_PREMISES;
             STOP_SERVICEON_PREMISES = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.STOP_SERVICEON_PREMISES;
             SAVE_AND_SHOW_PACKAGES = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.SAVE_AND_SHOW_PACKAGES;
             INCOMPLETE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.INCOMPLETE;
             ISSUE_DETECTED_STATE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.ISSUE_DETECTED_STATE;
             STOP = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.STOP;
             SYNC = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.SYNC;
             DELETE_SEQUENCE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.DELETE_SEQUENCE;
             MATCH_EVENT_LINK_UNLINK = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.MATCH_EVENT_LINK_UNLINK;
             GET_NEXT_NUMBER = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.GET_NEXT_NUMBER;
             ASSIGN_LANDLORD = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.ASSIGN_LANDLORD;
             VALIDATE_DEVICE_TEST = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.VALIDATE_DEVICE_TEST;
             SUPERVISOR_ASSIGNMENT = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.SUPERVISOR_ASSIGNMENT;
             ASSIGN_PARENT_PREMISE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.ASSIGN_PARENT_PREMISE;
             SUBMIT_FOR_APPROVAL = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.SUBMIT_FOR_APPROVAL;
             FREEZE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.FREEZE;
             REOPEN_QUOTE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.REOPEN_QUOTE;
             PAYMENT_DISTRIBUTE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.PAYMENT_DISTRIBUTE;
             RESENT = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.RESENT;
             ACTIVE = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.ACTIVE;
             SEND_BACK = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.SEND_BACK;
             AWAITING_PROCESS = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.AWAITING_PROCESS;
             REMOVE_LANDLORD = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.REMOVE_LANDLORD;
             RECEIPT_VERIFICATION_STATE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.RECEIPT_VERIFICATION_STATE;
             INACTIVE = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.INACTIVE;
             REMOVE_PARENT_PREMISE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.REMOVE_PARENT_PREMISE;
             REJECTED_STATE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.REJECTED_STATE;
             REOPEN = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.REOPEN;
             TRANSFER = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.TRANSFER;
             CANCEL_SELECTED = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.CANCEL_SELECTED;
             ASSIGN = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.ASSIGN;
             AWAITING_ACKNOWLEDGEMENT = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.AWAITING_ACKNOWLEDGEMENT;
             REINSTATE_SA = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.REINSTATE_SA;
             INACTIVATE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.INACTIVATE;
             BREAK = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.BREAK;
             AWAITING_BILL_DETERMINANT = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.AWAITING_BILL_DETERMINANT;
             TERMINATED = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.TERMINATED;
             REVERT = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.REVERT;
             ADD = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.ADD;
             CORRECTION_NOTE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.CORRECTION_NOTE;
             STOP_AUTOPAY = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.STOP_AUTOPAY;
             CONFIRM_MANUAL_AMOUNTS = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.CONFIRM_MANUAL_AMOUNTS;
             SET_SEQUENCE_NUMBER = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.SET_SEQUENCE_NUMBER;
             REOPEN_TO_DO = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.REOPEN_TO_DO;
             CALCULATING_BILL_SEGMENT = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.CALCULATING_BILL_SEGMENT;
             RESTORE_REVISION = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.RESTORE_REVISION;
             SUCCESS = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.SUCCESS;
             UNDO = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.UNDO;
             CREATE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.CREATE;
             START = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.START;
             CLOSE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.CLOSE;
             SNAPSHOT = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.SNAPSHOT;
             DETERMINE_IF_TOP_UP_NEEDED = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.DETERMINE_IF_TOP_UP_NEEDED;
             CLOSE_QUOTE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.CLOSE_QUOTE;
             COPY_APPOINTMENTS = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.COPY_APPOINTMENTS;
             UNDO_CORRECTION_NOTE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.UNDO_CORRECTION_NOTE;
             DELETE = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.DELETE;
             CANCEL_QUOTE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.CANCEL_QUOTE;
             ALL_PAYMENT_DISTRIBUTE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.ALL_PAYMENT_DISTRIBUTE;
             REMOVE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.REMOVE;
             DERIVE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.DERIVE;
             REBILL = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.REBILL;
             PAYMENT_CANCEL = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.PAYMENT_CANCEL;
             SUPER_USER = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.SUPER_USER;
             LINKED = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.LINKED;
             UPDATE_SELECTED = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.UPDATE_SELECTED;
             SYNCHRONIZED = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.SYNCHRONIZED;
             TRANSFER_STOCK_LOCATION_ITEM = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.TRANSFER_STOCK_LOCATION_ITEM;
             DETERMINE_APPROVERS = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.DETERMINE_APPROVERS;
             SEND_REQ = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.SEND_REQ;
             HOLD = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.HOLD;
             TRANSFER_STOCK_LOCATION_METER = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.TRANSFER_STOCK_LOCATION_METER;
             CANCEL_REBILL_FREEZE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.CANCEL_REBILL_FREEZE;
             MIGRATION_APPROVED = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.MIGRATION_APPROVED;
             VALIDATE_STATE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.VALIDATE_STATE;
             FREEZE_COMPLETE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.FREEZE_COMPLETE;
             VERIFICATION_STATE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.VERIFICATION_STATE;
             COMPLETE_QUOTE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.COMPLETE_QUOTE;
             MIGRATION_CANCEL_APPLY = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.MIGRATION_CANCEL_APPLY;
             SEND_REQUEST = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.SEND_REQUEST;
             MESSAGE_SENT = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.MESSAGE_SENT;
             DISPLAY_LETTER = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.DISPLAY_LETTER;
             INQUIRE = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.INQUIRE;
             TRANSFER_DISTRIBUTION_RULE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.TRANSFER_DISTRIBUTION_RULE;
             CANCEL_PROPOSAL_SA = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.CANCEL_PROPOSAL_SA;
             PROCESSING_ERROR = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.PROCESSING_ERROR;
             DETERMINE_SYNC_NEEDED = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.DETERMINE_SYNC_NEEDED;
             GENERATE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.GENERATE;
             COMPLETE = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.COMPLETE;
             DELETE_ENTITY = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.DELETE_ENTITY;
             CANCELLED = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.CANCELLED;
             CREATE_SUB_SA = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.CREATE_SUB_SA;
             TRUE_UP = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.TRUE_UP;
             DISCARD = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.DISCARD;
             SUBMIT_VIEW_REPORT = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.SUBMIT_VIEW_REPORT;
             CALLBACK = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.CALLBACK;
             EXECUTE = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.EXECUTE;
             GET_NEXT_TO_DO_ASSIGNED_TO_YOU = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.GET_NEXT_TO_DO_ASSIGNED_TO_YOU;
             TRIGGER_EVENTS = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.TRIGGER_EVENTS;
             CANCEL_FROZEN = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.CANCEL_FROZEN;
             ACTIVATE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.ACTIVATE;
             OBJECTED = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.OBJECTED;
             INITIATE_CANCEL = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.INITIATE_CANCEL;
             EXPIRE_SERVICE_AGREEMENT_RELATIONSHIP = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.EXPIRE_SERVICE_AGREEMENT_RELATIONSHIP;
             CAPTURE_FINAL_SNAPSHOT = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.CAPTURE_FINAL_SNAPSHOT;
             WITHDRAW = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.WITHDRAW;
             TOU_DERIVE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.TOU_DERIVE;
             SYNC_ERROR = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.SYNC_ERROR;
             CANCEL_EVENT = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.CANCEL_EVENT;
             NO_APPROVAL_NECESSARY = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.NO_APPROVAL_NECESSARY;
             PAYMENT_FREEZE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.PAYMENT_FREEZE;
             MIGRATION_NEEDS_REVIEW = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.MIGRATION_NEEDS_REVIEW;
             BILL_DETERMINANTS_PROCESSED = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.BILL_DETERMINANTS_PROCESSED;
             NO_RESPONSE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.NO_RESPONSE;
             AWAITING_DATA_SYNC = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.AWAITING_DATA_SYNC;
             NO_PROCESSING_REQUIRED = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.NO_PROCESSING_REQUIRED;
             VALIDATION_ERROR_STATE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.VALIDATION_ERROR_STATE;
             MIGRATION_REJECTED = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.MIGRATION_REJECTED;
             MIGRATION_CANNOT_APPLY = (AccessModeLookup) com.splwg.base.api.lookup.AccessModeLookup.constants.MIGRATION_CANNOT_APPLY;
             OTHER = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.OTHER;
             VALIDATED = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.VALIDATED;
             PAYMENT_DELETE = (AccessModeLookup) com.splwg.ccb.api.lookup.AccessModeLookup.constants.PAYMENT_DELETE;
        }
    }

    //~ Methods ----------------------------------------------------------------------------------------------

    /* helper tester methods */
    /**
      * @return true if this Lookup represents awaitingCancelation
      */
    public boolean isAwaitingCancelation();
    /**
      * @return true if this Lookup represents cmMask
      */
    public boolean isCmMask();
    /**
      * @return true if this Lookup represents cmShow
      */
    public boolean isCmShow();


}