/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupGen.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupGen.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;

import com.splwg.base.support.impl.AbstractComponentLookup;

/**
 * AddModeLookup_Gen is a generated implementation class for the lookup field CI_ADD_MODE_FLG
 *
 * @author Generated by splDev.artifactGenerator
 */
public  class AddModeLookup_Gen
    extends AbstractComponentLookup
           <AddModeLookup>
     {

    /**
      * @return field name this class represents
      */
    @Override
    public String fieldName() {
        return "CI_ADD_MODE_FLG               ";
    }
    /* helper tester methods */
    /**
      * @return true if this Lookup represents the lookup value batchDemoData
      */
    public boolean isBatchDemoData() {
        return getLookup().equals(AddModeLookup.constants.BATCH_DEMO_DATA);
    }
    /**
      * @return true if this Lookup represents the lookup value onlineDemoData
      */
    public boolean isOnlineDemoData() {
        return getLookup().equals(AddModeLookup.constants.ONLINE_DEMO_DATA);
    }
}