/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupGen.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupGen.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;


/**
 * BadLineReasonLookup_Gen is a generated implementation class for the lookup field C1_BAD_LINE_RSN_FLG
 *
 * @author Generated by splDev.artifactGenerator
 */
public  class BadLineReasonLookup_Gen
    extends com.splwg.ccb.api.lookup.BadLineReasonLookup_Gen
     {

    /* helper tester methods */
    /**
      * @return true if this Lookup represents the lookup value illegible
      */
    public boolean isIllegible() {
        return getLookup().equals(BadLineReasonLookup.constants.ILLEGIBLE);
    }
}