/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupGen.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupGen.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;

import com.splwg.base.support.impl.AbstractComponentLookup;

/**
 * BillMethodForDemoDataCreationLookup_Gen is a generated implementation class for the lookup field CI_BILL_METH_FLG
 *
 * @author Generated by splDev.artifactGenerator
 */
public  class BillMethodForDemoDataCreationLookup_Gen
    extends AbstractComponentLookup
           <BillMethodForDemoDataCreationLookup>
     {

    /**
      * @return field name this class represents
      */
    @Override
    public String fieldName() {
        return "CI_BILL_METH_FLG              ";
    }
    /* helper tester methods */
    /**
      * @return true if this Lookup represents the lookup value billCycleSchedule
      */
    public boolean isBillCycleSchedule() {
        return getLookup().equals(BillMethodForDemoDataCreationLookup.constants.BILL_CYCLE_SCHEDULE);
    }
    /**
      * @return true if this Lookup represents the lookup value masterConfigurationSchedule
      */
    public boolean isMasterConfigurationSchedule() {
        return getLookup().equals(BillMethodForDemoDataCreationLookup.constants.MASTER_CONFIGURATION_SCHEDULE);
    }
}