/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupInterface.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupInterface.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;

import com.splwg.base.api.datatypes.Lookup;
import com.splwg.base.api.datatypes.LookupHelper;

/**
 * BillMethodForDemoDataCreationLookup is a class that represents the lookup field CI_BILL_METH_FLG
 * and its values:
   <table>
     <tr> <th>FIELD_VALUE</th> <th>Property Name</th> <th>Description</th> </tr>
     <tr> <td>CIBS</td> <td>billCycleSchedule</td>
             <td>Based on Bill Cycle Schedule</td> </tr>
     <tr> <td>CIMS</td> <td>masterConfigurationSchedule</td>
             <td>Based on Maser Config Billing Schedule</td> </tr>
    </table>
 * stored on the tables CI_LOOKUP_FIELD, CI_LOOKUP_VALUE.
 *
 * @author Generated by splDev.artifactGenerator
 */
public interface BillMethodForDemoDataCreationLookup extends Lookup {

    //~ Static fields/initializers ---------------------------------------------------------------------------

    /* constants */
    public static final Constants constants = new Constants();
    
    public static class Constants {
        // New values
        /** Constant value representing lookup value for billCycleSchedule (value = 'CIBS')*/
        public BillMethodForDemoDataCreationLookup BILL_CYCLE_SCHEDULE; 
        /** Constant value representing lookup value for masterConfigurationSchedule (value = 'CIMS')*/
        public BillMethodForDemoDataCreationLookup MASTER_CONFIGURATION_SCHEDULE; 
        // Old Values

        public void initialize() {
            // new values
            BILL_CYCLE_SCHEDULE = 
                LookupHelper.getLookupInstance(BillMethodForDemoDataCreationLookup.class, "CIBS");

            MASTER_CONFIGURATION_SCHEDULE = 
                LookupHelper.getLookupInstance(BillMethodForDemoDataCreationLookup.class, "CIMS");

           // original values
        }
    }

    //~ Methods ----------------------------------------------------------------------------------------------

    /* helper tester methods */
    /**
      * @return true if this Lookup represents billCycleSchedule
      */
    public boolean isBillCycleSchedule();
    /**
      * @return true if this Lookup represents masterConfigurationSchedule
      */
    public boolean isMasterConfigurationSchedule();


}