/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupGen.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupGen.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;


/**
 * BusinessObjectOptionLookup_Gen is a generated implementation class for the lookup field BUS_OBJ_OPT_FLG
 *
 * @author Generated by splDev.artifactGenerator
 */
public  class BusinessObjectOptionLookup_Gen
    extends com.splwg.ccb.api.lookup.BusinessObjectOptionLookup_Impl
     {

    /* helper tester methods */
    /**
      * @return true if this Lookup represents the lookup value filepathLaunch
      */
    public boolean isFilepathLaunch() {
        return getLookup().equals(BusinessObjectOptionLookup.constants.FILEPATH_LAUNCH);
    }
    /**
      * @return true if this Lookup represents the lookup value smtpServer
      */
    public boolean isSmtpServer() {
        return getLookup().equals(BusinessObjectOptionLookup.constants.SMTP_SERVER);
    }
    /**
      * @return true if this Lookup represents the lookup value customerContactType
      */
    public boolean isCustomerContactType() {
        return getLookup().equals(BusinessObjectOptionLookup.constants.CUSTOMER_CONTACT_TYPE);
    }
    /**
      * @return true if this Lookup represents the lookup value customerContactClass
      */
    public boolean isCustomerContactClass() {
        return getLookup().equals(BusinessObjectOptionLookup.constants.CUSTOMER_CONTACT_CLASS);
    }
    /**
      * @return true if this Lookup represents the lookup value filepathEmail
      */
    public boolean isFilepathEmail() {
        return getLookup().equals(BusinessObjectOptionLookup.constants.FILEPATH_EMAIL);
    }
    /**
      * @return true if this Lookup represents the lookup value infoMap
      */
    public boolean isInfoMap() {
        return getLookup().equals(BusinessObjectOptionLookup.constants.INFO_MAP);
    }
    /**
      * @return true if this Lookup represents the lookup value leadCompletionScript
      */
    public boolean isLeadCompletionScript() {
        return getLookup().equals(BusinessObjectOptionLookup.constants.LEAD_COMPLETION_SCRIPT);
    }
}