/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupInterface.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupInterface.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;

import com.splwg.base.api.datatypes.LookupHelper;

/**
 * BusinessObjectOptionLookup is a class that represents the lookup field BUS_OBJ_OPT_FLG
 * and its values:
   <table>
     <tr> <th>FIELD_VALUE</th> <th>Property Name</th> <th>Description</th> </tr>
     <tr> <td>CMPL</td> <td>filepathLaunch</td>
             <td>File Directory (Launching Files)</td> </tr>
     <tr> <td>CMES</td> <td>smtpServer</td>
             <td>SMTP Server</td> </tr>
     <tr> <td>CMCT</td> <td>customerContactType</td>
             <td>Denial Customer Contact Type</td> </tr>
     <tr> <td>CMCC</td> <td>customerContactClass</td>
             <td>Denial Customer Contact Class</td> </tr>
     <tr> <td>CMPE</td> <td>filepathEmail</td>
             <td>File Directory (Emailing Files)</td> </tr>
     <tr> <td>CMIM</td> <td>infoMap</td>
             <td>Information Map</td> </tr>
     <tr> <td>CMLC</td> <td>leadCompletionScript</td>
             <td>Lead Completion Script</td> </tr>
    </table>
 * stored on the tables CI_LOOKUP_FIELD, CI_LOOKUP_VALUE.
 *
 * @author Generated by splDev.artifactGenerator
 */
public interface BusinessObjectOptionLookup extends com.splwg.ccb.api.lookup.BusinessObjectOptionLookup {

    //~ Static fields/initializers ---------------------------------------------------------------------------

    /* constants */
    public static final Constants constants = new Constants();
    
    public static class Constants {
        // New values
        /** Constant value representing lookup value for filepathLaunch (value = 'CMPL')*/
        public BusinessObjectOptionLookup FILEPATH_LAUNCH; 
        /** Constant value representing lookup value for smtpServer (value = 'CMES')*/
        public BusinessObjectOptionLookup SMTP_SERVER; 
        /** Constant value representing lookup value for customerContactType (value = 'CMCT')*/
        public BusinessObjectOptionLookup CUSTOMER_CONTACT_TYPE; 
        /** Constant value representing lookup value for customerContactClass (value = 'CMCC')*/
        public BusinessObjectOptionLookup CUSTOMER_CONTACT_CLASS; 
        /** Constant value representing lookup value for filepathEmail (value = 'CMPE')*/
        public BusinessObjectOptionLookup FILEPATH_EMAIL; 
        /** Constant value representing lookup value for infoMap (value = 'CMIM')*/
        public BusinessObjectOptionLookup INFO_MAP; 
        /** Constant value representing lookup value for leadCompletionScript (value = 'CMLC')*/
        public BusinessObjectOptionLookup LEAD_COMPLETION_SCRIPT; 
        // Old Values
        /** Constant value representing lookup value for rebateClaimContactPersonBO (value = 'C1CP')*/
        public BusinessObjectOptionLookup REBATE_CLAIM_CONTACT_PERSON_B_O; 
        /** Constant value representing lookup value for businessObjectToRead (value = 'F1BO')*/
        public BusinessObjectOptionLookup BUSINESS_OBJECT_TO_READ; 
        /** Constant value representing lookup value for serviceCategoryCharType (value = 'C1CT')*/
        public BusinessObjectOptionLookup SERVICE_CATEGORY_CHAR_TYPE; 
        /** Constant value representing lookup value for addtnPostProcSS (value = 'C1PA')*/
        public BusinessObjectOptionLookup ADDTN_POST_PROC_S_S; 
        /** Constant value representing lookup value for tenderDataSet (value = 'C1TD')*/
        public BusinessObjectOptionLookup TENDER_DATA_SET; 
        /** Constant value representing lookup value for supportedFileExtension (value = 'F1SE')*/
        public BusinessObjectOptionLookup SUPPORTED_FILE_EXTENSION; 
        /** Constant value representing lookup value for creditCardNumberFormatValidationServiceScript (value = 'C1CV')*/
        public BusinessObjectOptionLookup CREDIT_CARD_NUMBER_FORMAT_VALIDATION_SERVICE_SCRIPT; 
        /** Constant value representing lookup value for activityRequestPreviewDerivation (value = 'C1PD')*/
        public BusinessObjectOptionLookup ACTIVITY_REQUEST_PREVIEW_DERIVATION; 
        /** Constant value representing lookup value for relatedTransBO (value = 'F1BX')*/
        public BusinessObjectOptionLookup RELATED_TRANS_B_O; 
        /** Constant value representing lookup value for leadBO (value = 'C1LB')*/
        public BusinessObjectOptionLookup LEAD_B_O; 
        /** Constant value representing lookup value for touMapDataBo (value = 'C1TM')*/
        public BusinessObjectOptionLookup TOU_MAP_DATA_BO; 
        /** Constant value representing lookup value for templateBatchCtrlForLeadDisposition (value = 'C1LD')*/
        public BusinessObjectOptionLookup TEMPLATE_BATCH_CTRL_FOR_LEAD_DISPOSITION; 
        /** Constant value representing lookup value for templateBatchCtrlForLeadGeneration (value = 'C1LG')*/
        public BusinessObjectOptionLookup TEMPLATE_BATCH_CTRL_FOR_LEAD_GENERATION; 
        /** Constant value representing lookup value for statusReasonbusinessObject (value = 'F1SR')*/
        public BusinessObjectOptionLookup STATUS_REASONBUSINESS_OBJECT; 
        /** Constant value representing lookup value for displayMapSS (value = 'F1SS')*/
        public BusinessObjectOptionLookup DISPLAY_MAP_S_S; 
        /** Constant value representing lookup value for syncRequestDA (value = 'C1DA')*/
        public BusinessObjectOptionLookup SYNC_REQUEST_D_A; 
        /** Constant value representing lookup value for webServiceType (value = 'F1WT')*/
        public BusinessObjectOptionLookup WEB_SERVICE_TYPE; 
        /** Constant value representing lookup value for outboundMsgType (value = 'F1OM')*/
        public BusinessObjectOptionLookup OUTBOUND_MSG_TYPE; 
        /** Constant value representing lookup value for opaServerLocation (value = 'F1OS')*/
        public BusinessObjectOptionLookup OPA_SERVER_LOCATION; 
        /** Constant value representing lookup value for initiativeCritDeriveValAlgType (value = 'C1DE')*/
        public BusinessObjectOptionLookup INITIATIVE_CRIT_DERIVE_VAL_ALG_TYPE; 
        /** Constant value representing lookup value for productOfferReadBO (value = 'C1PR')*/
        public BusinessObjectOptionLookup PRODUCT_OFFER_READ_B_O; 
        /** Constant value representing lookup value for toDoCaseExceptionToDoTypeOption (value = 'C1TX')*/
        public BusinessObjectOptionLookup TO_DO_CASE_EXCEPTION_TO_DO_TYPE_OPTION; 
        /** Constant value representing lookup value for starSchemaType (value = 'F1SY')*/
        public BusinessObjectOptionLookup STAR_SCHEMA_TYPE; 
        /** Constant value representing lookup value for elementPopulationRule (value = 'F1EP')*/
        public BusinessObjectOptionLookup ELEMENT_POPULATION_RULE; 
        /** Constant value representing lookup value for actionsZoneUIMap (value = 'F1AM')*/
        public BusinessObjectOptionLookup ACTIONS_ZONE_U_I_MAP; 
        /** Constant value representing lookup value for extractBatchProcess (value = 'F1ET')*/
        public BusinessObjectOptionLookup EXTRACT_BATCH_PROCESS; 
        /** Constant value representing lookup value for opaRuleBasePath (value = 'F1RB')*/
        public BusinessObjectOptionLookup OPA_RULE_BASE_PATH; 
        /** Constant value representing lookup value for externalSys (value = 'F1EX')*/
        public BusinessObjectOptionLookup EXTERNAL_SYS; 
        /** Constant value representing lookup value for saCreationRuleBO (value = 'C1SA')*/
        public BusinessObjectOptionLookup SA_CREATION_RULE_B_O; 
        /** Constant value representing lookup value for serviceTaskClass (value = 'C1SC')*/
        public BusinessObjectOptionLookup SERVICE_TASK_CLASS; 
        /** Constant value representing lookup value for actionsZoneServiceScript (value = 'F1AS')*/
        public BusinessObjectOptionLookup ACTIONS_ZONE_SERVICE_SCRIPT; 
        /** Constant value representing lookup value for relatedAdministrationBO (value = 'F1AX')*/
        public BusinessObjectOptionLookup RELATED_ADMINISTRATION_B_O; 
        /** Constant value representing lookup value for compatibilityMode21 (value = 'F121')*/
        public BusinessObjectOptionLookup COMPATIBILITY_MODE_2_1; 
        /** Constant value representing lookup value for displayStatUImap (value = 'C1SM')*/
        public BusinessObjectOptionLookup DISPLAY_STAT_U_IMAP; 
        /** Constant value representing lookup value for initiativeSignUpMap (value = 'C1SP')*/
        public BusinessObjectOptionLookup INITIATIVE_SIGN_UP_MAP; 
        /** Constant value representing lookup value for saCreationRuleReadBO (value = 'C1SR')*/
        public BusinessObjectOptionLookup SA_CREATION_RULE_READ_B_O; 
        /** Constant value representing lookup value for portalNavOption (value = 'F1NO')*/
        public BusinessObjectOptionLookup PORTAL_NAV_OPTION; 
        /** Constant value representing lookup value for currencyConversionSS (value = 'C1CC')*/
        public BusinessObjectOptionLookup CURRENCY_CONVERSION_S_S; 
        /** Constant value representing lookup value for displayStatMapSS (value = 'C1SS')*/
        public BusinessObjectOptionLookup DISPLAY_STAT_MAP_S_S; 
        /** Constant value representing lookup value for binary (value = 'F1BI')*/
        public BusinessObjectOptionLookup BINARY; 
        /** Constant value representing lookup value for initiativeSignUpScript (value = 'C1SU')*/
        public BusinessObjectOptionLookup INITIATIVE_SIGN_UP_SCRIPT; 
        /** Constant value representing lookup value for elementBeingApproved (value = 'C1EL')*/
        public BusinessObjectOptionLookup ELEMENT_BEING_APPROVED; 
        /** Constant value representing lookup value for masterAdministrationBO (value = 'C1MX')*/
        public BusinessObjectOptionLookup MASTER_ADMINISTRATION_B_O; 
        /** Constant value representing lookup value for displayUImap (value = 'F1DU')*/
        public BusinessObjectOptionLookup DISPLAY_U_IMAP; 
        /** Constant value representing lookup value for aproveSS (value = 'C1AS')*/
        public BusinessObjectOptionLookup APROVE_S_S; 
        /** Constant value representing lookup value for rebateDefinitionBO (value = 'C1RD')*/
        public BusinessObjectOptionLookup REBATE_DEFINITION_B_O; 
        /** Constant value representing lookup value for inactiveAlgorithm (value = 'F1IA')*/
        public BusinessObjectOptionLookup INACTIVE_ALGORITHM; 
        /** Constant value representing lookup value for maintenanceBPA (value = 'F1MB')*/
        public BusinessObjectOptionLookup MAINTENANCE_B_P_A; 
        /** Constant value representing lookup value for managedContentXSL (value = 'F1MC')*/
        public BusinessObjectOptionLookup MANAGED_CONTENT_X_S_L; 
        /** Constant value representing lookup value for receiptVerificationUImap (value = 'C1VM')*/
        public BusinessObjectOptionLookup RECEIPT_VERIFICATION_U_IMAP; 
        /** Constant value representing lookup value for rebateClaimLineBO (value = 'C1RL')*/
        public BusinessObjectOptionLookup REBATE_CLAIM_LINE_B_O; 
        /** Constant value representing lookup value for addUpdateUImap (value = 'F1UU')*/
        public BusinessObjectOptionLookup ADD_UPDATE_U_IMAP; 
        /** Constant value representing lookup value for dataAreaMapper (value = 'F1MP')*/
        public BusinessObjectOptionLookup DATA_AREA_MAPPER; 
        /** Constant value representing lookup value for excludeBOFromDropdownList (value = 'C1FD')*/
        public BusinessObjectOptionLookup EXCLUDE_B_O_FROM_DROPDOWN_LIST; 
        /** Constant value representing lookup value for salesRepresentativeType (value = 'C1RP')*/
        public BusinessObjectOptionLookup SALES_REPRESENTATIVE_TYPE; 
        /** Constant value representing lookup value for optOutPreferenceBO (value = 'C1NO')*/
        public BusinessObjectOptionLookup OPT_OUT_PREFERENCE_B_O; 
        /** Constant value representing lookup value for rejectSS (value = 'C1RS')*/
        public BusinessObjectOptionLookup REJECT_S_S; 
        /** Constant value representing lookup value for contactPreferenceBO (value = 'C1NP')*/
        public BusinessObjectOptionLookup CONTACT_PREFERENCE_B_O; 
        /** Constant value representing lookup value for activityRequestPreviewMap (value = 'C1PV')*/
        public BusinessObjectOptionLookup ACTIVITY_REQUEST_PREVIEW_MAP; 
        /** Constant value representing lookup value for requestPreviewDerivation (value = 'F1PD')*/
        public BusinessObjectOptionLookup REQUEST_PREVIEW_DERIVATION; 
        /** Constant value representing lookup value for contentType (value = 'F1CT')*/
        public BusinessObjectOptionLookup CONTENT_TYPE; 
        /** Constant value representing lookup value for postProcSS (value = 'F1PO')*/
        public BusinessObjectOptionLookup POST_PROC_S_S; 
        /** Constant value representing lookup value for initiativeCriteriaType (value = 'C1IC')*/
        public BusinessObjectOptionLookup INITIATIVE_CRITERIA_TYPE; 
        /** Constant value representing lookup value for snapshotDataArea (value = 'F1DA')*/
        public BusinessObjectOptionLookup SNAPSHOT_DATA_AREA; 
        /** Constant value representing lookup value for postSS (value = 'F1PS')*/
        public BusinessObjectOptionLookup POST_S_S; 
        /** Constant value representing lookup value for preProcSS (value = 'F1PR')*/
        public BusinessObjectOptionLookup PRE_PROC_S_S; 
        /** Constant value representing lookup value for tenderTypeErrorProcessingServiceScript (value = 'C1AE')*/
        public BusinessObjectOptionLookup TENDER_TYPE_ERROR_PROCESSING_SERVICE_SCRIPT; 
        /** Constant value representing lookup value for requestPreviewMap (value = 'F1PV')*/
        public BusinessObjectOptionLookup REQUEST_PREVIEW_MAP; 

        public void initialize() {
            // new values
            FILEPATH_LAUNCH = 
                LookupHelper.getLookupInstance(BusinessObjectOptionLookup.class, "CMPL");

            SMTP_SERVER = 
                LookupHelper.getLookupInstance(BusinessObjectOptionLookup.class, "CMES");

            CUSTOMER_CONTACT_TYPE = 
                LookupHelper.getLookupInstance(BusinessObjectOptionLookup.class, "CMCT");

            CUSTOMER_CONTACT_CLASS = 
                LookupHelper.getLookupInstance(BusinessObjectOptionLookup.class, "CMCC");

            FILEPATH_EMAIL = 
                LookupHelper.getLookupInstance(BusinessObjectOptionLookup.class, "CMPE");

            INFO_MAP = 
                LookupHelper.getLookupInstance(BusinessObjectOptionLookup.class, "CMIM");

            LEAD_COMPLETION_SCRIPT = 
                LookupHelper.getLookupInstance(BusinessObjectOptionLookup.class, "CMLC");

           // original values
             REBATE_CLAIM_CONTACT_PERSON_B_O = (BusinessObjectOptionLookup) com.splwg.ccb.api.lookup.BusinessObjectOptionLookup.constants.REBATE_CLAIM_CONTACT_PERSON_B_O;
             BUSINESS_OBJECT_TO_READ = (BusinessObjectOptionLookup) com.splwg.base.api.lookup.BusinessObjectOptionLookup.constants.BUSINESS_OBJECT_TO_READ;
             SERVICE_CATEGORY_CHAR_TYPE = (BusinessObjectOptionLookup) com.splwg.ccb.api.lookup.BusinessObjectOptionLookup.constants.SERVICE_CATEGORY_CHAR_TYPE;
             ADDTN_POST_PROC_S_S = (BusinessObjectOptionLookup) com.splwg.ccb.api.lookup.BusinessObjectOptionLookup.constants.ADDTN_POST_PROC_S_S;
             TENDER_DATA_SET = (BusinessObjectOptionLookup) com.splwg.ccb.api.lookup.BusinessObjectOptionLookup.constants.TENDER_DATA_SET;
             SUPPORTED_FILE_EXTENSION = (BusinessObjectOptionLookup) com.splwg.base.api.lookup.BusinessObjectOptionLookup.constants.SUPPORTED_FILE_EXTENSION;
             CREDIT_CARD_NUMBER_FORMAT_VALIDATION_SERVICE_SCRIPT = (BusinessObjectOptionLookup) com.splwg.ccb.api.lookup.BusinessObjectOptionLookup.constants.CREDIT_CARD_NUMBER_FORMAT_VALIDATION_SERVICE_SCRIPT;
             ACTIVITY_REQUEST_PREVIEW_DERIVATION = (BusinessObjectOptionLookup) com.splwg.ccb.api.lookup.BusinessObjectOptionLookup.constants.ACTIVITY_REQUEST_PREVIEW_DERIVATION;
             RELATED_TRANS_B_O = (BusinessObjectOptionLookup) com.splwg.base.api.lookup.BusinessObjectOptionLookup.constants.RELATED_TRANS_B_O;
             LEAD_B_O = (BusinessObjectOptionLookup) com.splwg.ccb.api.lookup.BusinessObjectOptionLookup.constants.LEAD_B_O;
             TOU_MAP_DATA_BO = (BusinessObjectOptionLookup) com.splwg.ccb.api.lookup.BusinessObjectOptionLookup.constants.TOU_MAP_DATA_BO;
             TEMPLATE_BATCH_CTRL_FOR_LEAD_DISPOSITION = (BusinessObjectOptionLookup) com.splwg.ccb.api.lookup.BusinessObjectOptionLookup.constants.TEMPLATE_BATCH_CTRL_FOR_LEAD_DISPOSITION;
             TEMPLATE_BATCH_CTRL_FOR_LEAD_GENERATION = (BusinessObjectOptionLookup) com.splwg.ccb.api.lookup.BusinessObjectOptionLookup.constants.TEMPLATE_BATCH_CTRL_FOR_LEAD_GENERATION;
             STATUS_REASONBUSINESS_OBJECT = (BusinessObjectOptionLookup) com.splwg.base.api.lookup.BusinessObjectOptionLookup.constants.STATUS_REASONBUSINESS_OBJECT;
             DISPLAY_MAP_S_S = (BusinessObjectOptionLookup) com.splwg.base.api.lookup.BusinessObjectOptionLookup.constants.DISPLAY_MAP_S_S;
             SYNC_REQUEST_D_A = (BusinessObjectOptionLookup) com.splwg.ccb.api.lookup.BusinessObjectOptionLookup.constants.SYNC_REQUEST_D_A;
             WEB_SERVICE_TYPE = (BusinessObjectOptionLookup) com.splwg.base.api.lookup.BusinessObjectOptionLookup.constants.WEB_SERVICE_TYPE;
             OUTBOUND_MSG_TYPE = (BusinessObjectOptionLookup) com.splwg.base.api.lookup.BusinessObjectOptionLookup.constants.OUTBOUND_MSG_TYPE;
             OPA_SERVER_LOCATION = (BusinessObjectOptionLookup) com.splwg.base.api.lookup.BusinessObjectOptionLookup.constants.OPA_SERVER_LOCATION;
             INITIATIVE_CRIT_DERIVE_VAL_ALG_TYPE = (BusinessObjectOptionLookup) com.splwg.ccb.api.lookup.BusinessObjectOptionLookup.constants.INITIATIVE_CRIT_DERIVE_VAL_ALG_TYPE;
             PRODUCT_OFFER_READ_B_O = (BusinessObjectOptionLookup) com.splwg.ccb.api.lookup.BusinessObjectOptionLookup.constants.PRODUCT_OFFER_READ_B_O;
             TO_DO_CASE_EXCEPTION_TO_DO_TYPE_OPTION = (BusinessObjectOptionLookup) com.splwg.ccb.api.lookup.BusinessObjectOptionLookup.constants.TO_DO_CASE_EXCEPTION_TO_DO_TYPE_OPTION;
             STAR_SCHEMA_TYPE = (BusinessObjectOptionLookup) com.splwg.base.api.lookup.BusinessObjectOptionLookup.constants.STAR_SCHEMA_TYPE;
             ELEMENT_POPULATION_RULE = (BusinessObjectOptionLookup) com.splwg.base.api.lookup.BusinessObjectOptionLookup.constants.ELEMENT_POPULATION_RULE;
             ACTIONS_ZONE_U_I_MAP = (BusinessObjectOptionLookup) com.splwg.base.api.lookup.BusinessObjectOptionLookup.constants.ACTIONS_ZONE_U_I_MAP;
             EXTRACT_BATCH_PROCESS = (BusinessObjectOptionLookup) com.splwg.base.api.lookup.BusinessObjectOptionLookup.constants.EXTRACT_BATCH_PROCESS;
             OPA_RULE_BASE_PATH = (BusinessObjectOptionLookup) com.splwg.base.api.lookup.BusinessObjectOptionLookup.constants.OPA_RULE_BASE_PATH;
             EXTERNAL_SYS = (BusinessObjectOptionLookup) com.splwg.base.api.lookup.BusinessObjectOptionLookup.constants.EXTERNAL_SYS;
             SA_CREATION_RULE_B_O = (BusinessObjectOptionLookup) com.splwg.ccb.api.lookup.BusinessObjectOptionLookup.constants.SA_CREATION_RULE_B_O;
             SERVICE_TASK_CLASS = (BusinessObjectOptionLookup) com.splwg.ccb.api.lookup.BusinessObjectOptionLookup.constants.SERVICE_TASK_CLASS;
             ACTIONS_ZONE_SERVICE_SCRIPT = (BusinessObjectOptionLookup) com.splwg.base.api.lookup.BusinessObjectOptionLookup.constants.ACTIONS_ZONE_SERVICE_SCRIPT;
             RELATED_ADMINISTRATION_B_O = (BusinessObjectOptionLookup) com.splwg.base.api.lookup.BusinessObjectOptionLookup.constants.RELATED_ADMINISTRATION_B_O;
             COMPATIBILITY_MODE_2_1 = (BusinessObjectOptionLookup) com.splwg.base.api.lookup.BusinessObjectOptionLookup.constants.COMPATIBILITY_MODE_2_1;
             DISPLAY_STAT_U_IMAP = (BusinessObjectOptionLookup) com.splwg.ccb.api.lookup.BusinessObjectOptionLookup.constants.DISPLAY_STAT_U_IMAP;
             INITIATIVE_SIGN_UP_MAP = (BusinessObjectOptionLookup) com.splwg.ccb.api.lookup.BusinessObjectOptionLookup.constants.INITIATIVE_SIGN_UP_MAP;
             SA_CREATION_RULE_READ_B_O = (BusinessObjectOptionLookup) com.splwg.ccb.api.lookup.BusinessObjectOptionLookup.constants.SA_CREATION_RULE_READ_B_O;
             PORTAL_NAV_OPTION = (BusinessObjectOptionLookup) com.splwg.base.api.lookup.BusinessObjectOptionLookup.constants.PORTAL_NAV_OPTION;
             CURRENCY_CONVERSION_S_S = (BusinessObjectOptionLookup) com.splwg.ccb.api.lookup.BusinessObjectOptionLookup.constants.CURRENCY_CONVERSION_S_S;
             DISPLAY_STAT_MAP_S_S = (BusinessObjectOptionLookup) com.splwg.ccb.api.lookup.BusinessObjectOptionLookup.constants.DISPLAY_STAT_MAP_S_S;
             BINARY = (BusinessObjectOptionLookup) com.splwg.base.api.lookup.BusinessObjectOptionLookup.constants.BINARY;
             INITIATIVE_SIGN_UP_SCRIPT = (BusinessObjectOptionLookup) com.splwg.ccb.api.lookup.BusinessObjectOptionLookup.constants.INITIATIVE_SIGN_UP_SCRIPT;
             ELEMENT_BEING_APPROVED = (BusinessObjectOptionLookup) com.splwg.ccb.api.lookup.BusinessObjectOptionLookup.constants.ELEMENT_BEING_APPROVED;
             MASTER_ADMINISTRATION_B_O = (BusinessObjectOptionLookup) com.splwg.ccb.api.lookup.BusinessObjectOptionLookup.constants.MASTER_ADMINISTRATION_B_O;
             DISPLAY_U_IMAP = (BusinessObjectOptionLookup) com.splwg.base.api.lookup.BusinessObjectOptionLookup.constants.DISPLAY_U_IMAP;
             APROVE_S_S = (BusinessObjectOptionLookup) com.splwg.ccb.api.lookup.BusinessObjectOptionLookup.constants.APROVE_S_S;
             REBATE_DEFINITION_B_O = (BusinessObjectOptionLookup) com.splwg.ccb.api.lookup.BusinessObjectOptionLookup.constants.REBATE_DEFINITION_B_O;
             INACTIVE_ALGORITHM = (BusinessObjectOptionLookup) com.splwg.base.api.lookup.BusinessObjectOptionLookup.constants.INACTIVE_ALGORITHM;
             MAINTENANCE_B_P_A = (BusinessObjectOptionLookup) com.splwg.base.api.lookup.BusinessObjectOptionLookup.constants.MAINTENANCE_B_P_A;
             MANAGED_CONTENT_X_S_L = (BusinessObjectOptionLookup) com.splwg.base.api.lookup.BusinessObjectOptionLookup.constants.MANAGED_CONTENT_X_S_L;
             RECEIPT_VERIFICATION_U_IMAP = (BusinessObjectOptionLookup) com.splwg.ccb.api.lookup.BusinessObjectOptionLookup.constants.RECEIPT_VERIFICATION_U_IMAP;
             REBATE_CLAIM_LINE_B_O = (BusinessObjectOptionLookup) com.splwg.ccb.api.lookup.BusinessObjectOptionLookup.constants.REBATE_CLAIM_LINE_B_O;
             ADD_UPDATE_U_IMAP = (BusinessObjectOptionLookup) com.splwg.base.api.lookup.BusinessObjectOptionLookup.constants.ADD_UPDATE_U_IMAP;
             DATA_AREA_MAPPER = (BusinessObjectOptionLookup) com.splwg.base.api.lookup.BusinessObjectOptionLookup.constants.DATA_AREA_MAPPER;
             EXCLUDE_B_O_FROM_DROPDOWN_LIST = (BusinessObjectOptionLookup) com.splwg.ccb.api.lookup.BusinessObjectOptionLookup.constants.EXCLUDE_B_O_FROM_DROPDOWN_LIST;
             SALES_REPRESENTATIVE_TYPE = (BusinessObjectOptionLookup) com.splwg.ccb.api.lookup.BusinessObjectOptionLookup.constants.SALES_REPRESENTATIVE_TYPE;
             OPT_OUT_PREFERENCE_B_O = (BusinessObjectOptionLookup) com.splwg.ccb.api.lookup.BusinessObjectOptionLookup.constants.OPT_OUT_PREFERENCE_B_O;
             REJECT_S_S = (BusinessObjectOptionLookup) com.splwg.ccb.api.lookup.BusinessObjectOptionLookup.constants.REJECT_S_S;
             CONTACT_PREFERENCE_B_O = (BusinessObjectOptionLookup) com.splwg.ccb.api.lookup.BusinessObjectOptionLookup.constants.CONTACT_PREFERENCE_B_O;
             ACTIVITY_REQUEST_PREVIEW_MAP = (BusinessObjectOptionLookup) com.splwg.ccb.api.lookup.BusinessObjectOptionLookup.constants.ACTIVITY_REQUEST_PREVIEW_MAP;
             REQUEST_PREVIEW_DERIVATION = (BusinessObjectOptionLookup) com.splwg.base.api.lookup.BusinessObjectOptionLookup.constants.REQUEST_PREVIEW_DERIVATION;
             CONTENT_TYPE = (BusinessObjectOptionLookup) com.splwg.base.api.lookup.BusinessObjectOptionLookup.constants.CONTENT_TYPE;
             POST_PROC_S_S = (BusinessObjectOptionLookup) com.splwg.base.api.lookup.BusinessObjectOptionLookup.constants.POST_PROC_S_S;
             INITIATIVE_CRITERIA_TYPE = (BusinessObjectOptionLookup) com.splwg.ccb.api.lookup.BusinessObjectOptionLookup.constants.INITIATIVE_CRITERIA_TYPE;
             SNAPSHOT_DATA_AREA = (BusinessObjectOptionLookup) com.splwg.base.api.lookup.BusinessObjectOptionLookup.constants.SNAPSHOT_DATA_AREA;
             POST_S_S = (BusinessObjectOptionLookup) com.splwg.base.api.lookup.BusinessObjectOptionLookup.constants.POST_S_S;
             PRE_PROC_S_S = (BusinessObjectOptionLookup) com.splwg.base.api.lookup.BusinessObjectOptionLookup.constants.PRE_PROC_S_S;
             TENDER_TYPE_ERROR_PROCESSING_SERVICE_SCRIPT = (BusinessObjectOptionLookup) com.splwg.ccb.api.lookup.BusinessObjectOptionLookup.constants.TENDER_TYPE_ERROR_PROCESSING_SERVICE_SCRIPT;
             REQUEST_PREVIEW_MAP = (BusinessObjectOptionLookup) com.splwg.base.api.lookup.BusinessObjectOptionLookup.constants.REQUEST_PREVIEW_MAP;
        }
    }

    //~ Methods ----------------------------------------------------------------------------------------------

    /* helper tester methods */
    /**
      * @return true if this Lookup represents filepathLaunch
      */
    public boolean isFilepathLaunch();
    /**
      * @return true if this Lookup represents smtpServer
      */
    public boolean isSmtpServer();
    /**
      * @return true if this Lookup represents customerContactType
      */
    public boolean isCustomerContactType();
    /**
      * @return true if this Lookup represents customerContactClass
      */
    public boolean isCustomerContactClass();
    /**
      * @return true if this Lookup represents filepathEmail
      */
    public boolean isFilepathEmail();
    /**
      * @return true if this Lookup represents infoMap
      */
    public boolean isInfoMap();
    /**
      * @return true if this Lookup represents leadCompletionScript
      */
    public boolean isLeadCompletionScript();


}