/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupGen.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupGen.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;


/**
 * CcbSelfServiceAlertTypeLookup_Gen is a generated implementation class for the lookup field WX_CCB_ALERT_TYPE_FLG
 *
 * @author Generated by splDev.artifactGenerator
 */
public  class CcbSelfServiceAlertTypeLookup_Gen
    extends com.splwg.ccb.api.lookup.CcbSelfServiceAlertTypeLookup_Gen
     {

    /* helper tester methods */
    /**
      * @return true if this Lookup represents the lookup value generalAlertMessages
      */
    public boolean isGeneralAlertMessages() {
        return getLookup().equals(CcbSelfServiceAlertTypeLookup.constants.GENERAL_ALERT_MESSAGES);
    }
}