/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupInterface.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupInterface.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;

import com.splwg.base.api.datatypes.Lookup;
import com.splwg.base.api.datatypes.LookupHelper;

/**
 * CiprocessingTypeLookup is a class that represents the lookup field CI_PROCESSING_TYPE
 * and its values:
   <table>
     <tr> <th>FIELD_VALUE</th> <th>Property Name</th> <th>Description</th> </tr>
     <tr> <td>CICC</td> <td>customerContactManagerBO</td>
             <td>Customer Contact Manager BO</td> </tr>
     <tr> <td>CICS</td> <td>caseManagerBO</td>
             <td>Case Manager BO</td> </tr>
     <tr> <td>CIPP</td> <td>payPlanManagerBO</td>
             <td>Pay Plan Manager BO</td> </tr>
     <tr> <td>CIRB</td> <td>realTimeBatchUsageBO</td>
             <td>Real-Time Batch Usage BO</td> </tr>
     <tr> <td>CITD</td> <td>toDoManagerBO</td>
             <td>To Do Manager BO</td> </tr>
     <tr> <td>CICR</td> <td>caseManagerCreatorBO</td>
             <td>Case Manager Creator BO</td> </tr>
     <tr> <td>CIRT</td> <td>realTimeOnlineUsageBO</td>
             <td>Real-Time Online Usage BO</td> </tr>
     <tr> <td>CIMD</td> <td>masterDemoDataCreatorBO</td>
             <td>Master Demo Data Creator BO</td> </tr>
     <tr> <td>CIAM</td> <td>accountManagerBO</td>
             <td>Account Manager BO</td> </tr>
     <tr> <td>CIBM</td> <td>billManagerBO</td>
             <td>Bill Manager BO</td> </tr>
     <tr> <td>CIPM</td> <td>paymentManagerBO</td>
             <td>Payment Manager BO</td> </tr>
    </table>
 * stored on the tables CI_LOOKUP_FIELD, CI_LOOKUP_VALUE.
 *
 * @author Generated by splDev.artifactGenerator
 */
public interface CiprocessingTypeLookup extends Lookup {

    //~ Static fields/initializers ---------------------------------------------------------------------------

    /* constants */
    public static final Constants constants = new Constants();
    
    public static class Constants {
        // New values
        /** Constant value representing lookup value for customerContactManagerBO (value = 'CICC')*/
        public CiprocessingTypeLookup CUSTOMER_CONTACT_MANAGER_B_O; 
        /** Constant value representing lookup value for caseManagerBO (value = 'CICS')*/
        public CiprocessingTypeLookup CASE_MANAGER_B_O; 
        /** Constant value representing lookup value for payPlanManagerBO (value = 'CIPP')*/
        public CiprocessingTypeLookup PAY_PLAN_MANAGER_B_O; 
        /** Constant value representing lookup value for realTimeBatchUsageBO (value = 'CIRB')*/
        public CiprocessingTypeLookup REAL_TIME_BATCH_USAGE_B_O; 
        /** Constant value representing lookup value for toDoManagerBO (value = 'CITD')*/
        public CiprocessingTypeLookup TO_DO_MANAGER_B_O; 
        /** Constant value representing lookup value for caseManagerCreatorBO (value = 'CICR')*/
        public CiprocessingTypeLookup CASE_MANAGER_CREATOR_B_O; 
        /** Constant value representing lookup value for realTimeOnlineUsageBO (value = 'CIRT')*/
        public CiprocessingTypeLookup REAL_TIME_ONLINE_USAGE_B_O; 
        /** Constant value representing lookup value for masterDemoDataCreatorBO (value = 'CIMD')*/
        public CiprocessingTypeLookup MASTER_DEMO_DATA_CREATOR_B_O; 
        /** Constant value representing lookup value for accountManagerBO (value = 'CIAM')*/
        public CiprocessingTypeLookup ACCOUNT_MANAGER_B_O; 
        /** Constant value representing lookup value for billManagerBO (value = 'CIBM')*/
        public CiprocessingTypeLookup BILL_MANAGER_B_O; 
        /** Constant value representing lookup value for paymentManagerBO (value = 'CIPM')*/
        public CiprocessingTypeLookup PAYMENT_MANAGER_B_O; 
        // Old Values

        public void initialize() {
            // new values
            CUSTOMER_CONTACT_MANAGER_B_O = 
                LookupHelper.getLookupInstance(CiprocessingTypeLookup.class, "CICC");

            CASE_MANAGER_B_O = 
                LookupHelper.getLookupInstance(CiprocessingTypeLookup.class, "CICS");

            PAY_PLAN_MANAGER_B_O = 
                LookupHelper.getLookupInstance(CiprocessingTypeLookup.class, "CIPP");

            REAL_TIME_BATCH_USAGE_B_O = 
                LookupHelper.getLookupInstance(CiprocessingTypeLookup.class, "CIRB");

            TO_DO_MANAGER_B_O = 
                LookupHelper.getLookupInstance(CiprocessingTypeLookup.class, "CITD");

            CASE_MANAGER_CREATOR_B_O = 
                LookupHelper.getLookupInstance(CiprocessingTypeLookup.class, "CICR");

            REAL_TIME_ONLINE_USAGE_B_O = 
                LookupHelper.getLookupInstance(CiprocessingTypeLookup.class, "CIRT");

            MASTER_DEMO_DATA_CREATOR_B_O = 
                LookupHelper.getLookupInstance(CiprocessingTypeLookup.class, "CIMD");

            ACCOUNT_MANAGER_B_O = 
                LookupHelper.getLookupInstance(CiprocessingTypeLookup.class, "CIAM");

            BILL_MANAGER_B_O = 
                LookupHelper.getLookupInstance(CiprocessingTypeLookup.class, "CIBM");

            PAYMENT_MANAGER_B_O = 
                LookupHelper.getLookupInstance(CiprocessingTypeLookup.class, "CIPM");

           // original values
        }
    }

    //~ Methods ----------------------------------------------------------------------------------------------

    /* helper tester methods */
    /**
      * @return true if this Lookup represents customerContactManagerBO
      */
    public boolean isCustomerContactManagerBO();
    /**
      * @return true if this Lookup represents caseManagerBO
      */
    public boolean isCaseManagerBO();
    /**
      * @return true if this Lookup represents payPlanManagerBO
      */
    public boolean isPayPlanManagerBO();
    /**
      * @return true if this Lookup represents realTimeBatchUsageBO
      */
    public boolean isRealTimeBatchUsageBO();
    /**
      * @return true if this Lookup represents toDoManagerBO
      */
    public boolean isToDoManagerBO();
    /**
      * @return true if this Lookup represents caseManagerCreatorBO
      */
    public boolean isCaseManagerCreatorBO();
    /**
      * @return true if this Lookup represents realTimeOnlineUsageBO
      */
    public boolean isRealTimeOnlineUsageBO();
    /**
      * @return true if this Lookup represents masterDemoDataCreatorBO
      */
    public boolean isMasterDemoDataCreatorBO();
    /**
      * @return true if this Lookup represents accountManagerBO
      */
    public boolean isAccountManagerBO();
    /**
      * @return true if this Lookup represents billManagerBO
      */
    public boolean isBillManagerBO();
    /**
      * @return true if this Lookup represents paymentManagerBO
      */
    public boolean isPaymentManagerBO();


}