/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupGen.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupGen.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;


/**
 * ContactDetailStatusLookup_Gen is a generated implementation class for the lookup field CND_VERIF_STATUS_FLG
 *
 * @author Generated by splDev.artifactGenerator
 */
public  class ContactDetailStatusLookup_Gen
    extends com.splwg.ccb.api.lookup.ContactDetailStatusLookup_Gen
     {

    /* helper tester methods */
    /**
      * @return true if this Lookup represents the lookup value pending
      */
    public boolean isPending() {
        return getLookup().equals(ContactDetailStatusLookup.constants.PENDING);
    }
    /**
      * @return true if this Lookup represents the lookup value bounced
      */
    public boolean isBounced() {
        return getLookup().equals(ContactDetailStatusLookup.constants.BOUNCED);
    }
    /**
      * @return true if this Lookup represents the lookup value verified
      */
    public boolean isVerified() {
        return getLookup().equals(ContactDetailStatusLookup.constants.VERIFIED);
    }
}