/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupInterface.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupInterface.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;

import com.splwg.base.api.datatypes.LookupHelper;

/**
 * HouseTypeLookup is a class that represents the lookup field HOUSE_TYPE
 * and its values:
   <table>
     <tr> <th>FIELD_VALUE</th> <th>Property Name</th> <th>Description</th> </tr>
     <tr> <td>WW  </td> <td>houseTrailerReference</td>
             <td>House Trailer Reference</td> </tr>
     <tr> <td>AB  </td> <td>houseBoatReference</td>
             <td>House Boat Reference</td> </tr>
    </table>
 * stored on the tables CI_LOOKUP_FIELD, CI_LOOKUP_VALUE.
 *
 * @author Generated by splDev.artifactGenerator
 */
public interface HouseTypeLookup extends com.splwg.ccb.api.lookup.HouseTypeLookup {

    //~ Static fields/initializers ---------------------------------------------------------------------------

    /* constants */
    public static final Constants constants = new Constants();
    
    public static class Constants {
        // New values
        /** Constant value representing lookup value for houseTrailerReference (value = 'WW  ')*/
        public HouseTypeLookup HOUSE_TRAILER_REFERENCE; 
        /** Constant value representing lookup value for houseBoatReference (value = 'AB  ')*/
        public HouseTypeLookup HOUSE_BOAT_REFERENCE; 
        // Old Values

        public void initialize() {
            // new values
            HOUSE_TRAILER_REFERENCE = 
                LookupHelper.getLookupInstance(HouseTypeLookup.class, "WW  ");

            HOUSE_BOAT_REFERENCE = 
                LookupHelper.getLookupInstance(HouseTypeLookup.class, "AB  ");

           // original values
        }
    }

    //~ Methods ----------------------------------------------------------------------------------------------

    /* helper tester methods */
    /**
      * @return true if this Lookup represents houseTrailerReference
      */
    public boolean isHouseTrailerReference();
    /**
      * @return true if this Lookup represents houseBoatReference
      */
    public boolean isHouseBoatReference();


}