/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupGen.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupGen.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;


/**
 * NotificationSelfServiceTaskTypeLookup_Gen is a generated implementation class for the lookup field C1_NF_SSTASK_TYPE_FLG
 *
 * @author Generated by splDev.artifactGenerator
 */
public  class NotificationSelfServiceTaskTypeLookup_Gen
    extends com.splwg.ccb.api.lookup.NotificationSelfServiceTaskTypeLookup_Gen
     {

    /* helper tester methods */
    /**
      * @return true if this Lookup represents the lookup value ssIssuesNotification
      */
    public boolean isSsIssuesNotification() {
        return getLookup().equals(NotificationSelfServiceTaskTypeLookup.constants.SS_ISSUES_NOTIFICATION);
    }
    /**
      * @return true if this Lookup represents the lookup value marketingCommunicationPreference
      */
    public boolean isMarketingCommunicationPreference() {
        return getLookup().equals(NotificationSelfServiceTaskTypeLookup.constants.MARKETING_COMMUNICATION_PREFERENCE);
    }
}