/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupGen.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupGen.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;


/**
 * OutageCallCancelReasonLookup_Gen is a generated implementation class for the lookup field C1_OUTCALL_CAN_RSN_FLG
 *
 * @author Generated by splDev.artifactGenerator
 */
public  class OutageCallCancelReasonLookup_Gen
    extends com.splwg.ccb.api.lookup.OutageCallCancelReasonLookup_Gen
     {

    /* helper tester methods */
    /**
      * @return true if this Lookup represents the lookup value outageCallCanceled
      */
    public boolean isOutageCallCanceled() {
        return getLookup().equals(OutageCallCancelReasonLookup.constants.OUTAGE_CALL_CANCELED);
    }
}