/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupInterface.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupInterface.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;

import com.splwg.base.api.datatypes.LookupHelper;

/**
 * OutageCallCancelReasonLookup is a class that represents the lookup field C1_OUTCALL_CAN_RSN_FLG
 * and its values:
   <table>
     <tr> <th>FIELD_VALUE</th> <th>Property Name</th> <th>Description</th> </tr>
     <tr> <td>CAN </td> <td>outageCallCanceled</td>
             <td>Outage Call Canceled</td> </tr>
    </table>
 * stored on the tables CI_LOOKUP_FIELD, CI_LOOKUP_VALUE.
 *
 * @author Generated by splDev.artifactGenerator
 */
public interface OutageCallCancelReasonLookup extends com.splwg.ccb.api.lookup.OutageCallCancelReasonLookup {

    //~ Static fields/initializers ---------------------------------------------------------------------------

    /* constants */
    public static final Constants constants = new Constants();
    
    public static class Constants {
        // New values
        /** Constant value representing lookup value for outageCallCanceled (value = 'CAN ')*/
        public OutageCallCancelReasonLookup OUTAGE_CALL_CANCELED; 
        // Old Values

        public void initialize() {
            // new values
            OUTAGE_CALL_CANCELED = 
                LookupHelper.getLookupInstance(OutageCallCancelReasonLookup.class, "CAN ");

           // original values
        }
    }

    //~ Methods ----------------------------------------------------------------------------------------------

    /* helper tester methods */
    /**
      * @return true if this Lookup represents outageCallCanceled
      */
    public boolean isOutageCallCanceled();


}