/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupGen.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupGen.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;


/**
 * RebateDefinitionProductLookup_Gen is a generated implementation class for the lookup field C1_RDEF_PRODUCT
 *
 * @author Generated by splDev.artifactGenerator
 */
public  class RebateDefinitionProductLookup_Gen
    extends com.splwg.ccb.api.lookup.RebateDefinitionProductLookup_Gen
     {

    /* helper tester methods */
    /**
      * @return true if this Lookup represents the lookup value coolRoofLowSlopeTier1
      */
    public boolean isCoolRoofLowSlopeTier1() {
        return getLookup().equals(RebateDefinitionProductLookup.constants.COOL_ROOF_LOW_SLOPE_TIER_1);
    }
    /**
      * @return true if this Lookup represents the lookup value wallInsulation
      */
    public boolean isWallInsulation() {
        return getLookup().equals(RebateDefinitionProductLookup.constants.WALL_INSULATION);
    }
    /**
      * @return true if this Lookup represents the lookup value coolRoofLowSlopeTier2
      */
    public boolean isCoolRoofLowSlopeTier2() {
        return getLookup().equals(RebateDefinitionProductLookup.constants.COOL_ROOF_LOW_SLOPE_TIER_2);
    }
    /**
      * @return true if this Lookup represents the lookup value highEffClothesWasher2
      */
    public boolean isHighEffClothesWasher2() {
        return getLookup().equals(RebateDefinitionProductLookup.constants.HIGH_EFF_CLOTHES_WASHER_2);
    }
    /**
      * @return true if this Lookup represents the lookup value coolRoofLowSlope
      */
    public boolean isCoolRoofLowSlope() {
        return getLookup().equals(RebateDefinitionProductLookup.constants.COOL_ROOF_LOW_SLOPE);
    }
    /**
      * @return true if this Lookup represents the lookup value highEffDishwasher1
      */
    public boolean isHighEffDishwasher1() {
        return getLookup().equals(RebateDefinitionProductLookup.constants.HIGH_EFF_DISHWASHER_1);
    }
    /**
      * @return true if this Lookup represents the lookup value atticInsulation
      */
    public boolean isAtticInsulation() {
        return getLookup().equals(RebateDefinitionProductLookup.constants.ATTIC_INSULATION);
    }
    /**
      * @return true if this Lookup represents the lookup value highEffClothesWasher1
      */
    public boolean isHighEffClothesWasher1() {
        return getLookup().equals(RebateDefinitionProductLookup.constants.HIGH_EFF_CLOTHES_WASHER_1);
    }
    /**
      * @return true if this Lookup represents the lookup value energyStarRoomAirConditioner
      */
    public boolean isEnergyStarRoomAirConditioner() {
        return getLookup().equals(RebateDefinitionProductLookup.constants.ENERGY_STAR_ROOM_AIR_CONDITIONER);
    }
    /**
      * @return true if this Lookup represents the lookup value highEffDishwasher2
      */
    public boolean isHighEffDishwasher2() {
        return getLookup().equals(RebateDefinitionProductLookup.constants.HIGH_EFF_DISHWASHER_2);
    }
}