/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupInterface.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupInterface.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;

import com.splwg.base.api.datatypes.LookupHelper;

/**
 * RebateClaimRejectReasonLookup is a class that represents the lookup field C1_REB_CLM_REJ_RSN_FLG
 * and its values:
   <table>
     <tr> <th>FIELD_VALUE</th> <th>Property Name</th> <th>Description</th> </tr>
     <tr> <td>BAD </td> <td>invalidData</td>
             <td>Invalid/missing data</td> </tr>
    </table>
 * stored on the tables CI_LOOKUP_FIELD, CI_LOOKUP_VALUE.
 *
 * @author Generated by splDev.artifactGenerator
 */
public interface RebateClaimRejectReasonLookup extends com.splwg.ccb.api.lookup.RebateClaimRejectReasonLookup {

    //~ Static fields/initializers ---------------------------------------------------------------------------

    /* constants */
    public static final Constants constants = new Constants();
    
    public static class Constants {
        // New values
        /** Constant value representing lookup value for invalidData (value = 'BAD ')*/
        public RebateClaimRejectReasonLookup INVALID_DATA; 
        // Old Values

        public void initialize() {
            // new values
            INVALID_DATA = 
                LookupHelper.getLookupInstance(RebateClaimRejectReasonLookup.class, "BAD ");

           // original values
        }
    }

    //~ Methods ----------------------------------------------------------------------------------------------

    /* helper tester methods */
    /**
      * @return true if this Lookup represents invalidData
      */
    public boolean isInvalidData();


}