/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupInterface.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupInterface.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;

import com.splwg.base.api.datatypes.LookupHelper;

/**
 * SyncRequestCancelReasonLookup is a class that represents the lookup field F1_SYNC_REQ_CANCEL_RSN_FLG
 * and its values:
   <table>
     <tr> <th>FIELD_VALUE</th> <th>Property Name</th> <th>Description</th> </tr>
     <tr> <td>CIUS</td> <td>cmSyncCancelByUser</td>
             <td>Canceled by User</td> </tr>
    </table>
 * stored on the tables CI_LOOKUP_FIELD, CI_LOOKUP_VALUE.
 *
 * @author Generated by splDev.artifactGenerator
 */
public interface SyncRequestCancelReasonLookup extends com.splwg.ccb.api.lookup.SyncRequestCancelReasonLookup {

    //~ Static fields/initializers ---------------------------------------------------------------------------

    /* constants */
    public static final Constants constants = new Constants();
    
    public static class Constants {
        // New values
        /** Constant value representing lookup value for cmSyncCancelByUser (value = 'CIUS')*/
        public SyncRequestCancelReasonLookup CM_SYNC_CANCEL_BY_USER; 
        // Old Values

        public void initialize() {
            // new values
            CM_SYNC_CANCEL_BY_USER = 
                LookupHelper.getLookupInstance(SyncRequestCancelReasonLookup.class, "CIUS");

           // original values
        }
    }

    //~ Methods ----------------------------------------------------------------------------------------------

    /* helper tester methods */
    /**
      * @return true if this Lookup represents cmSyncCancelByUser
      */
    public boolean isCmSyncCancelByUser();


}