/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupGen.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupGen.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;


/**
 * SyncRequestCancelReasonLookup_Gen is a generated implementation class for the lookup field F1_SYNC_REQ_CANCEL_RSN_FLG
 *
 * @author Generated by splDev.artifactGenerator
 */
public  class SyncRequestCancelReasonLookup_Gen
    extends com.splwg.ccb.api.lookup.SyncRequestCancelReasonLookup_Impl
     {

    /* helper tester methods */
    /**
      * @return true if this Lookup represents the lookup value cmSyncCancelByUser
      */
    public boolean isCmSyncCancelByUser() {
        return getLookup().equals(SyncRequestCancelReasonLookup.constants.CM_SYNC_CANCEL_BY_USER);
    }
}