/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupGen.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupGen.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;


/**
 * AccessModeLookup_Gen is a generated implementation class for the lookup field ACCESS_MODE
 *
 * @author Generated by splDev.artifactGenerator
 */
public  class AccessModeLookup_Gen
    extends com.splwg.ccb.api.lookup.AccessModeLookup_Impl
     {

    /* helper tester methods */
    /**
      * @return true if this Lookup represents the lookup value awaitingCancelation
      */
    public boolean isAwaitingCancelation() {
        return getLookup().equals(AccessModeLookup.constants.AWAITING_CANCELATION);
    }
    /**
      * @return true if this Lookup represents the lookup value cmMask
      */
    public boolean isCmMask() {
        return getLookup().equals(AccessModeLookup.constants.CM_MASK);
    }
    /**
      * @return true if this Lookup represents the lookup value cmShow
      */
    public boolean isCmShow() {
        return getLookup().equals(AccessModeLookup.constants.CM_SHOW);
    }
}