/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupInterface.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupInterface.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;

import com.splwg.base.api.datatypes.Lookup;
import com.splwg.base.api.datatypes.LookupHelper;

/**
 * AddModeLookup is a class that represents the lookup field CI_ADD_MODE_FLG
 * and its values:
   <table>
     <tr> <th>FIELD_VALUE</th> <th>Property Name</th> <th>Description</th> </tr>
     <tr> <td>CIBA</td> <td>batchDemoData</td>
             <td>Batch Demo Data Replication</td> </tr>
     <tr> <td>CION</td> <td>onlineDemoData</td>
             <td>Online Demo Data Replication</td> </tr>
    </table>
 * stored on the tables CI_LOOKUP_FIELD, CI_LOOKUP_VALUE.
 *
 * @author Generated by splDev.artifactGenerator
 */
public interface AddModeLookup extends Lookup {

    //~ Static fields/initializers ---------------------------------------------------------------------------

    /* constants */
    public static final Constants constants = new Constants();
    
    public static class Constants {
        // New values
        /** Constant value representing lookup value for batchDemoData (value = 'CIBA')*/
        public AddModeLookup BATCH_DEMO_DATA; 
        /** Constant value representing lookup value for onlineDemoData (value = 'CION')*/
        public AddModeLookup ONLINE_DEMO_DATA; 
        // Old Values

        public void initialize() {
            // new values
            BATCH_DEMO_DATA = 
                LookupHelper.getLookupInstance(AddModeLookup.class, "CIBA");

            ONLINE_DEMO_DATA = 
                LookupHelper.getLookupInstance(AddModeLookup.class, "CION");

           // original values
        }
    }

    //~ Methods ----------------------------------------------------------------------------------------------

    /* helper tester methods */
    /**
      * @return true if this Lookup represents batchDemoData
      */
    public boolean isBatchDemoData();
    /**
      * @return true if this Lookup represents onlineDemoData
      */
    public boolean isOnlineDemoData();


}