/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupGen.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupGen.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;


/**
 * ApprovalRequestRejectReasonLookup_Gen is a generated implementation class for the lookup field C1_AREQ_REJECT_RSN_FLG
 *
 * @author Generated by splDev.artifactGenerator
 */
public  class ApprovalRequestRejectReasonLookup_Gen
    extends com.splwg.ccb.api.lookup.ApprovalRequestRejectReasonLookup_Gen
     {

    /* helper tester methods */
    /**
      * @return true if this Lookup represents the lookup value incorrectAdjustment
      */
    public boolean isIncorrectAdjustment() {
        return getLookup().equals(ApprovalRequestRejectReasonLookup.constants.INCORRECT_ADJUSTMENT);
    }
}