/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupInterface.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupInterface.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;

import com.splwg.base.api.datatypes.LookupHelper;

/**
 * ApprovalRequestRejectReasonLookup is a class that represents the lookup field C1_AREQ_REJECT_RSN_FLG
 * and its values:
   <table>
     <tr> <th>FIELD_VALUE</th> <th>Property Name</th> <th>Description</th> </tr>
     <tr> <td>OOPS</td> <td>incorrectAdjustment</td>
             <td>Incorrect Adjustment</td> </tr>
    </table>
 * stored on the tables CI_LOOKUP_FIELD, CI_LOOKUP_VALUE.
 *
 * @author Generated by splDev.artifactGenerator
 */
public interface ApprovalRequestRejectReasonLookup extends com.splwg.ccb.api.lookup.ApprovalRequestRejectReasonLookup {

    //~ Static fields/initializers ---------------------------------------------------------------------------

    /* constants */
    public static final Constants constants = new Constants();
    
    public static class Constants {
        // New values
        /** Constant value representing lookup value for incorrectAdjustment (value = 'OOPS')*/
        public ApprovalRequestRejectReasonLookup INCORRECT_ADJUSTMENT; 
        // Old Values

        public void initialize() {
            // new values
            INCORRECT_ADJUSTMENT = 
                LookupHelper.getLookupInstance(ApprovalRequestRejectReasonLookup.class, "OOPS");

           // original values
        }
    }

    //~ Methods ----------------------------------------------------------------------------------------------

    /* helper tester methods */
    /**
      * @return true if this Lookup represents incorrectAdjustment
      */
    public boolean isIncorrectAdjustment();


}