/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupInterface.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupInterface.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;

import com.splwg.base.api.datatypes.LookupHelper;

/**
 * CcbSelfServiceAlertTypeLookup is a class that represents the lookup field WX_CCB_ALERT_TYPE_FLG
 * and its values:
   <table>
     <tr> <th>FIELD_VALUE</th> <th>Property Name</th> <th>Description</th> </tr>
     <tr> <td>CMGA</td> <td>generalAlertMessages</td>
             <td>General Alert Messages</td> </tr>
    </table>
 * stored on the tables CI_LOOKUP_FIELD, CI_LOOKUP_VALUE.
 *
 * @author Generated by splDev.artifactGenerator
 */
public interface CcbSelfServiceAlertTypeLookup extends com.splwg.ccb.api.lookup.CcbSelfServiceAlertTypeLookup {

    //~ Static fields/initializers ---------------------------------------------------------------------------

    /* constants */
    public static final Constants constants = new Constants();
    
    public static class Constants {
        // New values
        /** Constant value representing lookup value for generalAlertMessages (value = 'CMGA')*/
        public CcbSelfServiceAlertTypeLookup GENERAL_ALERT_MESSAGES; 
        // Old Values
        /** Constant value representing lookup value for activePayArrPayPlan (value = 'C1AP')*/
        public CcbSelfServiceAlertTypeLookup ACTIVE_PAY_ARR_PAY_PLAN; 
        /** Constant value representing lookup value for prepayBillerInformation (value = 'C1PP')*/
        public CcbSelfServiceAlertTypeLookup PREPAY_BILLER_INFORMATION; 
        /** Constant value representing lookup value for budgetEnrollment (value = 'WXBE')*/
        public CcbSelfServiceAlertTypeLookup BUDGET_ENROLLMENT; 
        /** Constant value representing lookup value for outstandingBalance (value = 'C1OB')*/
        public CcbSelfServiceAlertTypeLookup OUTSTANDING_BALANCE; 
        /** Constant value representing lookup value for highlightPendingStartStop (value = 'C1PS')*/
        public CcbSelfServiceAlertTypeLookup HIGHLIGHT_PENDING_START_STOP; 
        /** Constant value representing lookup value for highlightOpenServiceTasks (value = 'C1OT')*/
        public CcbSelfServiceAlertTypeLookup HIGHLIGHT_OPEN_SERVICE_TASKS; 

        public void initialize() {
            // new values
            GENERAL_ALERT_MESSAGES = 
                LookupHelper.getLookupInstance(CcbSelfServiceAlertTypeLookup.class, "CMGA");

           // original values
             ACTIVE_PAY_ARR_PAY_PLAN = (CcbSelfServiceAlertTypeLookup) com.splwg.ccb.api.lookup.CcbSelfServiceAlertTypeLookup.constants.ACTIVE_PAY_ARR_PAY_PLAN;
             PREPAY_BILLER_INFORMATION = (CcbSelfServiceAlertTypeLookup) com.splwg.ccb.api.lookup.CcbSelfServiceAlertTypeLookup.constants.PREPAY_BILLER_INFORMATION;
             BUDGET_ENROLLMENT = (CcbSelfServiceAlertTypeLookup) com.splwg.ccb.api.lookup.CcbSelfServiceAlertTypeLookup.constants.BUDGET_ENROLLMENT;
             OUTSTANDING_BALANCE = (CcbSelfServiceAlertTypeLookup) com.splwg.ccb.api.lookup.CcbSelfServiceAlertTypeLookup.constants.OUTSTANDING_BALANCE;
             HIGHLIGHT_PENDING_START_STOP = (CcbSelfServiceAlertTypeLookup) com.splwg.ccb.api.lookup.CcbSelfServiceAlertTypeLookup.constants.HIGHLIGHT_PENDING_START_STOP;
             HIGHLIGHT_OPEN_SERVICE_TASKS = (CcbSelfServiceAlertTypeLookup) com.splwg.ccb.api.lookup.CcbSelfServiceAlertTypeLookup.constants.HIGHLIGHT_OPEN_SERVICE_TASKS;
        }
    }

    //~ Methods ----------------------------------------------------------------------------------------------

    /* helper tester methods */
    /**
      * @return true if this Lookup represents generalAlertMessages
      */
    public boolean isGeneralAlertMessages();


}