/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupGen.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupGen.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;

import com.splwg.base.support.impl.AbstractComponentLookup;

/**
 * CiprocessingTypeLookup_Gen is a generated implementation class for the lookup field CI_PROCESSING_TYPE
 *
 * @author Generated by splDev.artifactGenerator
 */
public  class CiprocessingTypeLookup_Gen
    extends AbstractComponentLookup
           <CiprocessingTypeLookup>
     {

    /**
      * @return field name this class represents
      */
    @Override
    public String fieldName() {
        return "CI_PROCESSING_TYPE            ";
    }
    /* helper tester methods */
    /**
      * @return true if this Lookup represents the lookup value customerContactManagerBO
      */
    public boolean isCustomerContactManagerBO() {
        return getLookup().equals(CiprocessingTypeLookup.constants.CUSTOMER_CONTACT_MANAGER_B_O);
    }
    /**
      * @return true if this Lookup represents the lookup value caseManagerBO
      */
    public boolean isCaseManagerBO() {
        return getLookup().equals(CiprocessingTypeLookup.constants.CASE_MANAGER_B_O);
    }
    /**
      * @return true if this Lookup represents the lookup value payPlanManagerBO
      */
    public boolean isPayPlanManagerBO() {
        return getLookup().equals(CiprocessingTypeLookup.constants.PAY_PLAN_MANAGER_B_O);
    }
    /**
      * @return true if this Lookup represents the lookup value realTimeBatchUsageBO
      */
    public boolean isRealTimeBatchUsageBO() {
        return getLookup().equals(CiprocessingTypeLookup.constants.REAL_TIME_BATCH_USAGE_B_O);
    }
    /**
      * @return true if this Lookup represents the lookup value toDoManagerBO
      */
    public boolean isToDoManagerBO() {
        return getLookup().equals(CiprocessingTypeLookup.constants.TO_DO_MANAGER_B_O);
    }
    /**
      * @return true if this Lookup represents the lookup value caseManagerCreatorBO
      */
    public boolean isCaseManagerCreatorBO() {
        return getLookup().equals(CiprocessingTypeLookup.constants.CASE_MANAGER_CREATOR_B_O);
    }
    /**
      * @return true if this Lookup represents the lookup value realTimeOnlineUsageBO
      */
    public boolean isRealTimeOnlineUsageBO() {
        return getLookup().equals(CiprocessingTypeLookup.constants.REAL_TIME_ONLINE_USAGE_B_O);
    }
    /**
      * @return true if this Lookup represents the lookup value masterDemoDataCreatorBO
      */
    public boolean isMasterDemoDataCreatorBO() {
        return getLookup().equals(CiprocessingTypeLookup.constants.MASTER_DEMO_DATA_CREATOR_B_O);
    }
    /**
      * @return true if this Lookup represents the lookup value accountManagerBO
      */
    public boolean isAccountManagerBO() {
        return getLookup().equals(CiprocessingTypeLookup.constants.ACCOUNT_MANAGER_B_O);
    }
    /**
      * @return true if this Lookup represents the lookup value billManagerBO
      */
    public boolean isBillManagerBO() {
        return getLookup().equals(CiprocessingTypeLookup.constants.BILL_MANAGER_B_O);
    }
    /**
      * @return true if this Lookup represents the lookup value paymentManagerBO
      */
    public boolean isPaymentManagerBO() {
        return getLookup().equals(CiprocessingTypeLookup.constants.PAYMENT_MANAGER_B_O);
    }
}