/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupInterface.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupInterface.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;

import com.splwg.base.api.datatypes.Lookup;
import com.splwg.base.api.datatypes.LookupHelper;

/**
 * CmShowAllMRsLookup is a class that represents the lookup field CM_SHOW_ALL_MRS
 * and its values:
   <table>
     <tr> <th>FIELD_VALUE</th> <th>Property Name</th> <th>Description</th> </tr>
     <tr> <td>Y   </td> <td>yes</td>
             <td>Yes</td> </tr>
    </table>
 * stored on the tables CI_LOOKUP_FIELD, CI_LOOKUP_VALUE.
 *
 * @author Generated by splDev.artifactGenerator
 */
public interface CmShowAllMRsLookup extends Lookup {

    //~ Static fields/initializers ---------------------------------------------------------------------------

    /* constants */
    public static final Constants constants = new Constants();
    
    public static class Constants {
        // New values
        /** Constant value representing lookup value for yes (value = 'Y   ')*/
        public CmShowAllMRsLookup YES; 
        // Old Values

        public void initialize() {
            // new values
            YES = 
                LookupHelper.getLookupInstance(CmShowAllMRsLookup.class, "Y   ");

           // original values
        }
    }

    //~ Methods ----------------------------------------------------------------------------------------------

    /* helper tester methods */
    /**
      * @return true if this Lookup represents yes
      */
    public boolean isYes();


}