/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupInterface.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupInterface.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;

import com.splwg.base.api.datatypes.LookupHelper;

/**
 * ContactDetailStatusLookup is a class that represents the lookup field CND_VERIF_STATUS_FLG
 * and its values:
   <table>
     <tr> <th>FIELD_VALUE</th> <th>Property Name</th> <th>Description</th> </tr>
     <tr> <td>PEND</td> <td>pending</td>
             <td>Pending</td> </tr>
     <tr> <td>BNCD</td> <td>bounced</td>
             <td>Bounced</td> </tr>
     <tr> <td>VERF</td> <td>verified</td>
             <td>Verified</td> </tr>
    </table>
 * stored on the tables CI_LOOKUP_FIELD, CI_LOOKUP_VALUE.
 *
 * @author Generated by splDev.artifactGenerator
 */
public interface ContactDetailStatusLookup extends com.splwg.ccb.api.lookup.ContactDetailStatusLookup {

    //~ Static fields/initializers ---------------------------------------------------------------------------

    /* constants */
    public static final Constants constants = new Constants();
    
    public static class Constants {
        // New values
        /** Constant value representing lookup value for pending (value = 'PEND')*/
        public ContactDetailStatusLookup PENDING; 
        /** Constant value representing lookup value for bounced (value = 'BNCD')*/
        public ContactDetailStatusLookup BOUNCED; 
        /** Constant value representing lookup value for verified (value = 'VERF')*/
        public ContactDetailStatusLookup VERIFIED; 
        // Old Values

        public void initialize() {
            // new values
            PENDING = 
                LookupHelper.getLookupInstance(ContactDetailStatusLookup.class, "PEND");

            BOUNCED = 
                LookupHelper.getLookupInstance(ContactDetailStatusLookup.class, "BNCD");

            VERIFIED = 
                LookupHelper.getLookupInstance(ContactDetailStatusLookup.class, "VERF");

           // original values
        }
    }

    //~ Methods ----------------------------------------------------------------------------------------------

    /* helper tester methods */
    /**
      * @return true if this Lookup represents pending
      */
    public boolean isPending();
    /**
      * @return true if this Lookup represents bounced
      */
    public boolean isBounced();
    /**
      * @return true if this Lookup represents verified
      */
    public boolean isVerified();


}