/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupInterface.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupInterface.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;

import com.splwg.base.api.datatypes.LookupHelper;

/**
 * CustomerRequestDiscardReasonLookup is a class that represents the lookup field C1_CUSTREQ_DISCARD_RSN_FLG
 * and its values:
   <table>
     <tr> <th>FIELD_VALUE</th> <th>Property Name</th> <th>Description</th> </tr>
     <tr> <td>USER</td> <td>cssUserDiscard</td>
             <td>Discarded by User</td> </tr>
    </table>
 * stored on the tables CI_LOOKUP_FIELD, CI_LOOKUP_VALUE.
 *
 * @author Generated by splDev.artifactGenerator
 */
public interface CustomerRequestDiscardReasonLookup extends com.splwg.ccb.api.lookup.CustomerRequestDiscardReasonLookup {

    //~ Static fields/initializers ---------------------------------------------------------------------------

    /* constants */
    public static final Constants constants = new Constants();
    
    public static class Constants {
        // New values
        /** Constant value representing lookup value for cssUserDiscard (value = 'USER')*/
        public CustomerRequestDiscardReasonLookup CSS_USER_DISCARD; 
        // Old Values

        public void initialize() {
            // new values
            CSS_USER_DISCARD = 
                LookupHelper.getLookupInstance(CustomerRequestDiscardReasonLookup.class, "USER");

           // original values
        }
    }

    //~ Methods ----------------------------------------------------------------------------------------------

    /* helper tester methods */
    /**
      * @return true if this Lookup represents cssUserDiscard
      */
    public boolean isCssUserDiscard();


}