/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupGen.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupGen.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;


/**
 * HouseType2Lookup_Gen is a generated implementation class for the lookup field HOUSE_TYPE2
 *
 * @author Generated by splDev.artifactGenerator
 */
public  class HouseType2Lookup_Gen
    extends com.splwg.ccb.api.lookup.HouseType2Lookup_Impl
     {

    /* helper tester methods */
    /**
      * @return true if this Lookup represents the lookup value houseBoatReference
      */
    public boolean isHouseBoatReference() {
        return getLookup().equals(HouseType2Lookup.constants.HOUSE_BOAT_REFERENCE);
    }
    /**
      * @return true if this Lookup represents the lookup value houseTrailerReference
      */
    public boolean isHouseTrailerReference() {
        return getLookup().equals(HouseType2Lookup.constants.HOUSE_TRAILER_REFERENCE);
    }
}