/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupGen.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupGen.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;

import com.splwg.base.support.impl.AbstractComponentLookup;

/**
 * IncludeMeterConfigurationLookup_Gen is a generated implementation class for the lookup field CM_INCL_MTRCONFIG_SW
 *
 * @author Generated by splDev.artifactGenerator
 */
public  class IncludeMeterConfigurationLookup_Gen
    extends AbstractComponentLookup
           <IncludeMeterConfigurationLookup>
     {

    /**
      * @return field name this class represents
      */
    @Override
    public String fieldName() {
        return "CM_INCL_MTRCONFIG_SW          ";
    }
    /* helper tester methods */
    /**
      * @return true if this Lookup represents the lookup value yes
      */
    public boolean isYes() {
        return getLookup().equals(IncludeMeterConfigurationLookup.constants.YES);
    }
}