/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupInterface.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupInterface.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;

import com.splwg.base.api.datatypes.LookupHelper;

/**
 * NotificationSelfServiceTaskTypeLookup is a class that represents the lookup field C1_NF_SSTASK_TYPE_FLG
 * and its values:
   <table>
     <tr> <th>FIELD_VALUE</th> <th>Property Name</th> <th>Description</th> </tr>
     <tr> <td>C1FI</td> <td>ssIssuesNotification</td>
             <td>$fieldValue.description</td> </tr>
     <tr> <td>C1MP</td> <td>marketingCommunicationPreference</td>
             <td>$fieldValue.description</td> </tr>
    </table>
 * stored on the tables CI_LOOKUP_FIELD, CI_LOOKUP_VALUE.
 *
 * @author Generated by splDev.artifactGenerator
 */
public interface NotificationSelfServiceTaskTypeLookup extends com.splwg.ccb.api.lookup.NotificationSelfServiceTaskTypeLookup {

    //~ Static fields/initializers ---------------------------------------------------------------------------

    /* constants */
    public static final Constants constants = new Constants();
    
    public static class Constants {
        // New values
        /** Constant value representing lookup value for ssIssuesNotification (value = 'C1FI')*/
        public NotificationSelfServiceTaskTypeLookup SS_ISSUES_NOTIFICATION; 
        /** Constant value representing lookup value for marketingCommunicationPreference (value = 'C1MP')*/
        public NotificationSelfServiceTaskTypeLookup MARKETING_COMMUNICATION_PREFERENCE; 
        // Old Values
        /** Constant value representing lookup value for ssPrepaidBillingPaymentRequestNotification (value = 'C1PP')*/
        public NotificationSelfServiceTaskTypeLookup SS_PREPAID_BILLING_PAYMENT_REQUEST_NOTIFICATION; 
        /** Constant value representing lookup value for ssPrepaidBillingNewChargeNotification (value = 'C1PC')*/
        public NotificationSelfServiceTaskTypeLookup SS_PREPAID_BILLING_NEW_CHARGE_NOTIFICATION; 
        /** Constant value representing lookup value for ssBillReadyNotification (value = 'WXBR')*/
        public NotificationSelfServiceTaskTypeLookup SS_BILL_READY_NOTIFICATION; 
        /** Constant value representing lookup value for ssLatePayNotification (value = 'WSLP')*/
        public NotificationSelfServiceTaskTypeLookup SS_LATE_PAY_NOTIFICATION; 
        /** Constant value representing lookup value for ssPaymentReceivedNotification (value = 'WSPR')*/
        public NotificationSelfServiceTaskTypeLookup SS_PAYMENT_RECEIVED_NOTIFICATION; 
        /** Constant value representing lookup value for ssBillDueNotification (value = 'WXBD')*/
        public NotificationSelfServiceTaskTypeLookup SS_BILL_DUE_NOTIFICATION; 

        public void initialize() {
            // new values
            SS_ISSUES_NOTIFICATION = 
                LookupHelper.getLookupInstance(NotificationSelfServiceTaskTypeLookup.class, "C1FI");

            MARKETING_COMMUNICATION_PREFERENCE = 
                LookupHelper.getLookupInstance(NotificationSelfServiceTaskTypeLookup.class, "C1MP");

           // original values
             SS_PREPAID_BILLING_PAYMENT_REQUEST_NOTIFICATION = (NotificationSelfServiceTaskTypeLookup) com.splwg.ccb.api.lookup.NotificationSelfServiceTaskTypeLookup.constants.SS_PREPAID_BILLING_PAYMENT_REQUEST_NOTIFICATION;
             SS_PREPAID_BILLING_NEW_CHARGE_NOTIFICATION = (NotificationSelfServiceTaskTypeLookup) com.splwg.ccb.api.lookup.NotificationSelfServiceTaskTypeLookup.constants.SS_PREPAID_BILLING_NEW_CHARGE_NOTIFICATION;
             SS_BILL_READY_NOTIFICATION = (NotificationSelfServiceTaskTypeLookup) com.splwg.ccb.api.lookup.NotificationSelfServiceTaskTypeLookup.constants.SS_BILL_READY_NOTIFICATION;
             SS_LATE_PAY_NOTIFICATION = (NotificationSelfServiceTaskTypeLookup) com.splwg.ccb.api.lookup.NotificationSelfServiceTaskTypeLookup.constants.SS_LATE_PAY_NOTIFICATION;
             SS_PAYMENT_RECEIVED_NOTIFICATION = (NotificationSelfServiceTaskTypeLookup) com.splwg.ccb.api.lookup.NotificationSelfServiceTaskTypeLookup.constants.SS_PAYMENT_RECEIVED_NOTIFICATION;
             SS_BILL_DUE_NOTIFICATION = (NotificationSelfServiceTaskTypeLookup) com.splwg.ccb.api.lookup.NotificationSelfServiceTaskTypeLookup.constants.SS_BILL_DUE_NOTIFICATION;
        }
    }

    //~ Methods ----------------------------------------------------------------------------------------------

    /* helper tester methods */
    /**
      * @return true if this Lookup represents ssIssuesNotification
      */
    public boolean isSsIssuesNotification();
    /**
      * @return true if this Lookup represents marketingCommunicationPreference
      */
    public boolean isMarketingCommunicationPreference();


}