/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupGen.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupGen.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;


/**
 * ProductComponentTypeLookup_Gen is a generated implementation class for the lookup field C1_PROD_COMP_TYPE_FLG
 *
 * @author Generated by splDev.artifactGenerator
 */
public  class ProductComponentTypeLookup_Gen
    extends com.splwg.ccb.api.lookup.ProductComponentTypeLookup_Gen
     {

    /* helper tester methods */
    /**
      * @return true if this Lookup represents the lookup value pricingComponent
      */
    public boolean isPricingComponent() {
        return getLookup().equals(ProductComponentTypeLookup.constants.PRICING_COMPONENT);
    }
    /**
      * @return true if this Lookup represents the lookup value otherComponent
      */
    public boolean isOtherComponent() {
        return getLookup().equals(ProductComponentTypeLookup.constants.OTHER_COMPONENT);
    }
}