/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupInterface.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupInterface.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;

import com.splwg.base.api.datatypes.LookupHelper;

/**
 * RebateDefinitionProductLookup is a class that represents the lookup field C1_RDEF_PRODUCT
 * and its values:
   <table>
     <tr> <th>FIELD_VALUE</th> <th>Property Name</th> <th>Description</th> </tr>
     <tr> <td>B03 </td> <td>coolRoofLowSlopeTier1</td>
             <td>Cool Roof Low Slope Tier 1</td> </tr>
     <tr> <td>B25 </td> <td>wallInsulation</td>
             <td>Wall Insulation</td> </tr>
     <tr> <td>B04 </td> <td>coolRoofLowSlopeTier2</td>
             <td>Cool Roof Low Slope Tier 2</td> </tr>
     <tr> <td>B34 </td> <td>highEffClothesWasher2</td>
             <td>High Efficiency Clothes Washer Level 2</td> </tr>
     <tr> <td>B02 </td> <td>coolRoofLowSlope</td>
             <td>Cool Roof Low Slope</td> </tr>
     <tr> <td>B35 </td> <td>highEffDishwasher1</td>
             <td>High Efficiency Dishwasher Level 1</td> </tr>
     <tr> <td>B11 </td> <td>atticInsulation</td>
             <td>Attic Insulation</td> </tr>
     <tr> <td>B33 </td> <td>highEffClothesWasher1</td>
             <td>High Efficiency Clothes Washer Level 1</td> </tr>
     <tr> <td>H169</td> <td>energyStarRoomAirConditioner</td>
             <td>Energy Star Room Air Conditioner</td> </tr>
     <tr> <td>B20 </td> <td>highEffDishwasher2</td>
             <td>High Efficiency Dishwasher Level 2</td> </tr>
    </table>
 * stored on the tables CI_LOOKUP_FIELD, CI_LOOKUP_VALUE.
 *
 * @author Generated by splDev.artifactGenerator
 */
public interface RebateDefinitionProductLookup extends com.splwg.ccb.api.lookup.RebateDefinitionProductLookup {

    //~ Static fields/initializers ---------------------------------------------------------------------------

    /* constants */
    public static final Constants constants = new Constants();
    
    public static class Constants {
        // New values
        /** Constant value representing lookup value for coolRoofLowSlopeTier1 (value = 'B03 ')*/
        public RebateDefinitionProductLookup COOL_ROOF_LOW_SLOPE_TIER_1; 
        /** Constant value representing lookup value for wallInsulation (value = 'B25 ')*/
        public RebateDefinitionProductLookup WALL_INSULATION; 
        /** Constant value representing lookup value for coolRoofLowSlopeTier2 (value = 'B04 ')*/
        public RebateDefinitionProductLookup COOL_ROOF_LOW_SLOPE_TIER_2; 
        /** Constant value representing lookup value for highEffClothesWasher2 (value = 'B34 ')*/
        public RebateDefinitionProductLookup HIGH_EFF_CLOTHES_WASHER_2; 
        /** Constant value representing lookup value for coolRoofLowSlope (value = 'B02 ')*/
        public RebateDefinitionProductLookup COOL_ROOF_LOW_SLOPE; 
        /** Constant value representing lookup value for highEffDishwasher1 (value = 'B35 ')*/
        public RebateDefinitionProductLookup HIGH_EFF_DISHWASHER_1; 
        /** Constant value representing lookup value for atticInsulation (value = 'B11 ')*/
        public RebateDefinitionProductLookup ATTIC_INSULATION; 
        /** Constant value representing lookup value for highEffClothesWasher1 (value = 'B33 ')*/
        public RebateDefinitionProductLookup HIGH_EFF_CLOTHES_WASHER_1; 
        /** Constant value representing lookup value for energyStarRoomAirConditioner (value = 'H169')*/
        public RebateDefinitionProductLookup ENERGY_STAR_ROOM_AIR_CONDITIONER; 
        /** Constant value representing lookup value for highEffDishwasher2 (value = 'B20 ')*/
        public RebateDefinitionProductLookup HIGH_EFF_DISHWASHER_2; 
        // Old Values

        public void initialize() {
            // new values
            COOL_ROOF_LOW_SLOPE_TIER_1 = 
                LookupHelper.getLookupInstance(RebateDefinitionProductLookup.class, "B03 ");

            WALL_INSULATION = 
                LookupHelper.getLookupInstance(RebateDefinitionProductLookup.class, "B25 ");

            COOL_ROOF_LOW_SLOPE_TIER_2 = 
                LookupHelper.getLookupInstance(RebateDefinitionProductLookup.class, "B04 ");

            HIGH_EFF_CLOTHES_WASHER_2 = 
                LookupHelper.getLookupInstance(RebateDefinitionProductLookup.class, "B34 ");

            COOL_ROOF_LOW_SLOPE = 
                LookupHelper.getLookupInstance(RebateDefinitionProductLookup.class, "B02 ");

            HIGH_EFF_DISHWASHER_1 = 
                LookupHelper.getLookupInstance(RebateDefinitionProductLookup.class, "B35 ");

            ATTIC_INSULATION = 
                LookupHelper.getLookupInstance(RebateDefinitionProductLookup.class, "B11 ");

            HIGH_EFF_CLOTHES_WASHER_1 = 
                LookupHelper.getLookupInstance(RebateDefinitionProductLookup.class, "B33 ");

            ENERGY_STAR_ROOM_AIR_CONDITIONER = 
                LookupHelper.getLookupInstance(RebateDefinitionProductLookup.class, "H169");

            HIGH_EFF_DISHWASHER_2 = 
                LookupHelper.getLookupInstance(RebateDefinitionProductLookup.class, "B20 ");

           // original values
        }
    }

    //~ Methods ----------------------------------------------------------------------------------------------

    /* helper tester methods */
    /**
      * @return true if this Lookup represents coolRoofLowSlopeTier1
      */
    public boolean isCoolRoofLowSlopeTier1();
    /**
      * @return true if this Lookup represents wallInsulation
      */
    public boolean isWallInsulation();
    /**
      * @return true if this Lookup represents coolRoofLowSlopeTier2
      */
    public boolean isCoolRoofLowSlopeTier2();
    /**
      * @return true if this Lookup represents highEffClothesWasher2
      */
    public boolean isHighEffClothesWasher2();
    /**
      * @return true if this Lookup represents coolRoofLowSlope
      */
    public boolean isCoolRoofLowSlope();
    /**
      * @return true if this Lookup represents highEffDishwasher1
      */
    public boolean isHighEffDishwasher1();
    /**
      * @return true if this Lookup represents atticInsulation
      */
    public boolean isAtticInsulation();
    /**
      * @return true if this Lookup represents highEffClothesWasher1
      */
    public boolean isHighEffClothesWasher1();
    /**
      * @return true if this Lookup represents energyStarRoomAirConditioner
      */
    public boolean isEnergyStarRoomAirConditioner();
    /**
      * @return true if this Lookup represents highEffDishwasher2
      */
    public boolean isHighEffDishwasher2();


}