/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupGen.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupGen.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;


/**
 * RebateClaimCancelReasonLookup_Gen is a generated implementation class for the lookup field C1_REB_CLM_CAN_RSN_FLG
 *
 * @author Generated by splDev.artifactGenerator
 */
public  class RebateClaimCancelReasonLookup_Gen
    extends com.splwg.ccb.api.lookup.RebateClaimCancelReasonLookup_Gen
     {

    /* helper tester methods */
    /**
      * @return true if this Lookup represents the lookup value invalidData
      */
    public boolean isInvalidData() {
        return getLookup().equals(RebateClaimCancelReasonLookup.constants.INVALID_DATA);
    }
}