/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupGen.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupGen.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;


/**
 * SchemaConstantOptionLookup_Gen is a generated implementation class for the lookup field F1CN_OPT_TYP_FLG
 *
 * @author Generated by splDev.artifactGenerator
 */
public  class SchemaConstantOptionLookup_Gen
    extends com.splwg.ccb.api.lookup.SchemaConstantOptionLookup_Impl
     {

    /* helper tester methods */
    /**
      * @return true if this Lookup represents the lookup value mobilePhone
      */
    public boolean isMobilePhone() {
        return getLookup().equals(SchemaConstantOptionLookup.constants.MOBILE_PHONE);
    }
}