/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupInterface.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupInterface.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;

import com.splwg.base.api.datatypes.LookupHelper;

/**
 * SchemaConstantOptionLookup is a class that represents the lookup field F1CN_OPT_TYP_FLG
 * and its values:
   <table>
     <tr> <th>FIELD_VALUE</th> <th>Property Name</th> <th>Description</th> </tr>
     <tr> <td>CIMP</td> <td>mobilePhone</td>
             <td>Mobile Phone Type</td> </tr>
    </table>
 * stored on the tables CI_LOOKUP_FIELD, CI_LOOKUP_VALUE.
 *
 * @author Generated by splDev.artifactGenerator
 */
public interface SchemaConstantOptionLookup extends com.splwg.ccb.api.lookup.SchemaConstantOptionLookup {

    //~ Static fields/initializers ---------------------------------------------------------------------------

    /* constants */
    public static final Constants constants = new Constants();
    
    public static class Constants {
        // New values
        /** Constant value representing lookup value for mobilePhone (value = 'CIMP')*/
        public SchemaConstantOptionLookup MOBILE_PHONE; 
        // Old Values
        /** Constant value representing lookup value for blockNumberCharType (value = 'C1BN')*/
        public SchemaConstantOptionLookup BLOCK_NUMBER_CHAR_TYPE; 
        /** Constant value representing lookup value for businessPhone (value = 'C1BP')*/
        public SchemaConstantOptionLookup BUSINESS_PHONE; 
        /** Constant value representing lookup value for contactPerAccountRelationshipType (value = 'C1CR')*/
        public SchemaConstantOptionLookup CONTACT_PER_ACCOUNT_RELATIONSHIP_TYPE; 
        /** Constant value representing lookup value for homePhone (value = 'C1HP')*/
        public SchemaConstantOptionLookup HOME_PHONE; 
        /** Constant value representing lookup value for contactNameCharType (value = 'C1CN')*/
        public SchemaConstantOptionLookup CONTACT_NAME_CHAR_TYPE; 
        /** Constant value representing lookup value for mainPhoneType (value = 'C1MA')*/
        public SchemaConstantOptionLookup MAIN_PHONE_TYPE; 
        /** Constant value representing lookup value for billRouteType (value = 'C1BR')*/
        public SchemaConstantOptionLookup BILL_ROUTE_TYPE; 
        /** Constant value representing lookup value for crossStreetNameCharType (value = 'C1CS')*/
        public SchemaConstantOptionLookup CROSS_STREET_NAME_CHAR_TYPE; 
        /** Constant value representing lookup value for cityCharType (value = 'C1CT')*/
        public SchemaConstantOptionLookup CITY_CHAR_TYPE; 
        /** Constant value representing lookup value for deviceGeo (value = 'C1DV')*/
        public SchemaConstantOptionLookup DEVICE_GEO; 
        /** Constant value representing lookup value for faxPhoneType (value = 'C1FX')*/
        public SchemaConstantOptionLookup FAX_PHONE_TYPE; 
        /** Constant value representing lookup value for streetNameCharType (value = 'C1SN')*/
        public SchemaConstantOptionLookup STREET_NAME_CHAR_TYPE; 
        /** Constant value representing lookup value for contactNumberCharType (value = 'C1NR')*/
        public SchemaConstantOptionLookup CONTACT_NUMBER_CHAR_TYPE; 
        /** Constant value representing lookup value for keyPriority (value = 'C1KP')*/
        public SchemaConstantOptionLookup KEY_PRIORITY; 
        /** Constant value representing lookup value for mainPerAccountRelationshipType (value = 'C1MR')*/
        public SchemaConstantOptionLookup MAIN_PER_ACCOUNT_RELATIONSHIP_TYPE; 
        /** Constant value representing lookup value for callIdentifierCharType (value = 'C1CI')*/
        public SchemaConstantOptionLookup CALL_IDENTIFIER_CHAR_TYPE; 
        /** Constant value representing lookup value for criticalPriority (value = 'C1IP')*/
        public SchemaConstantOptionLookup CRITICAL_PRIORITY; 
        /** Constant value representing lookup value for customerContactClass (value = 'C1CC')*/
        public SchemaConstantOptionLookup CUSTOMER_CONTACT_CLASS; 
        /** Constant value representing lookup value for latLong (value = 'C1LL')*/
        public SchemaConstantOptionLookup LAT_LONG; 
        /** Constant value representing lookup value for stateCharType (value = 'C1ST')*/
        public SchemaConstantOptionLookup STATE_CHAR_TYPE; 
        /** Constant value representing lookup value for medicalPriority (value = 'C1MP')*/
        public SchemaConstantOptionLookup MEDICAL_PRIORITY; 

        public void initialize() {
            // new values
            MOBILE_PHONE = 
                LookupHelper.getLookupInstance(SchemaConstantOptionLookup.class, "CIMP");

           // original values
             BLOCK_NUMBER_CHAR_TYPE = (SchemaConstantOptionLookup) com.splwg.ccb.api.lookup.SchemaConstantOptionLookup.constants.BLOCK_NUMBER_CHAR_TYPE;
             BUSINESS_PHONE = (SchemaConstantOptionLookup) com.splwg.ccb.api.lookup.SchemaConstantOptionLookup.constants.BUSINESS_PHONE;
             CONTACT_PER_ACCOUNT_RELATIONSHIP_TYPE = (SchemaConstantOptionLookup) com.splwg.ccb.api.lookup.SchemaConstantOptionLookup.constants.CONTACT_PER_ACCOUNT_RELATIONSHIP_TYPE;
             HOME_PHONE = (SchemaConstantOptionLookup) com.splwg.ccb.api.lookup.SchemaConstantOptionLookup.constants.HOME_PHONE;
             CONTACT_NAME_CHAR_TYPE = (SchemaConstantOptionLookup) com.splwg.ccb.api.lookup.SchemaConstantOptionLookup.constants.CONTACT_NAME_CHAR_TYPE;
             MAIN_PHONE_TYPE = (SchemaConstantOptionLookup) com.splwg.ccb.api.lookup.SchemaConstantOptionLookup.constants.MAIN_PHONE_TYPE;
             BILL_ROUTE_TYPE = (SchemaConstantOptionLookup) com.splwg.ccb.api.lookup.SchemaConstantOptionLookup.constants.BILL_ROUTE_TYPE;
             CROSS_STREET_NAME_CHAR_TYPE = (SchemaConstantOptionLookup) com.splwg.ccb.api.lookup.SchemaConstantOptionLookup.constants.CROSS_STREET_NAME_CHAR_TYPE;
             CITY_CHAR_TYPE = (SchemaConstantOptionLookup) com.splwg.ccb.api.lookup.SchemaConstantOptionLookup.constants.CITY_CHAR_TYPE;
             DEVICE_GEO = (SchemaConstantOptionLookup) com.splwg.ccb.api.lookup.SchemaConstantOptionLookup.constants.DEVICE_GEO;
             FAX_PHONE_TYPE = (SchemaConstantOptionLookup) com.splwg.ccb.api.lookup.SchemaConstantOptionLookup.constants.FAX_PHONE_TYPE;
             STREET_NAME_CHAR_TYPE = (SchemaConstantOptionLookup) com.splwg.ccb.api.lookup.SchemaConstantOptionLookup.constants.STREET_NAME_CHAR_TYPE;
             CONTACT_NUMBER_CHAR_TYPE = (SchemaConstantOptionLookup) com.splwg.ccb.api.lookup.SchemaConstantOptionLookup.constants.CONTACT_NUMBER_CHAR_TYPE;
             KEY_PRIORITY = (SchemaConstantOptionLookup) com.splwg.ccb.api.lookup.SchemaConstantOptionLookup.constants.KEY_PRIORITY;
             MAIN_PER_ACCOUNT_RELATIONSHIP_TYPE = (SchemaConstantOptionLookup) com.splwg.ccb.api.lookup.SchemaConstantOptionLookup.constants.MAIN_PER_ACCOUNT_RELATIONSHIP_TYPE;
             CALL_IDENTIFIER_CHAR_TYPE = (SchemaConstantOptionLookup) com.splwg.ccb.api.lookup.SchemaConstantOptionLookup.constants.CALL_IDENTIFIER_CHAR_TYPE;
             CRITICAL_PRIORITY = (SchemaConstantOptionLookup) com.splwg.ccb.api.lookup.SchemaConstantOptionLookup.constants.CRITICAL_PRIORITY;
             CUSTOMER_CONTACT_CLASS = (SchemaConstantOptionLookup) com.splwg.ccb.api.lookup.SchemaConstantOptionLookup.constants.CUSTOMER_CONTACT_CLASS;
             LAT_LONG = (SchemaConstantOptionLookup) com.splwg.ccb.api.lookup.SchemaConstantOptionLookup.constants.LAT_LONG;
             STATE_CHAR_TYPE = (SchemaConstantOptionLookup) com.splwg.ccb.api.lookup.SchemaConstantOptionLookup.constants.STATE_CHAR_TYPE;
             MEDICAL_PRIORITY = (SchemaConstantOptionLookup) com.splwg.ccb.api.lookup.SchemaConstantOptionLookup.constants.MEDICAL_PRIORITY;
        }
    }

    //~ Methods ----------------------------------------------------------------------------------------------

    /* helper tester methods */
    /**
      * @return true if this Lookup represents mobilePhone
      */
    public boolean isMobilePhone();


}