/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupGen.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupGen.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;

import com.splwg.base.support.impl.AbstractComponentLookup;

/**
 * ShowAllPremisesLookup_Gen is a generated implementation class for the lookup field CM_SHOWALLPREM
 *
 * @author Generated by splDev.artifactGenerator
 */
public  class ShowAllPremisesLookup_Gen
    extends AbstractComponentLookup
           <ShowAllPremisesLookup>
     {

    /**
      * @return field name this class represents
      */
    @Override
    public String fieldName() {
        return "CM_SHOWALLPREM                ";
    }
    /* helper tester methods */
    /**
      * @return true if this Lookup represents the lookup value showAllPremises
      */
    public boolean isShowAllPremises() {
        return getLookup().equals(ShowAllPremisesLookup.constants.SHOW_ALL_PREMISES);
    }
}