/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupInterface.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupInterface.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;

import com.splwg.base.api.datatypes.Lookup;
import com.splwg.base.api.datatypes.LookupHelper;

/**
 * UsageRequestTypeFlagLookup is a class that represents the lookup field CM_USAGE_TYPE_FLG
 * and its values:
   <table>
     <tr> <th>FIELD_VALUE</th> <th>Property Name</th> <th>Description</th> </tr>
     <tr> <td>C1IN</td> <td>interval</td>
             <td>Interval</td> </tr>
     <tr> <td>C1SC</td> <td>scalar</td>
             <td>Scalar</td> </tr>
    </table>
 * stored on the tables CI_LOOKUP_FIELD, CI_LOOKUP_VALUE.
 *
 * @author Generated by splDev.artifactGenerator
 */
public interface UsageRequestTypeFlagLookup extends Lookup {

    //~ Static fields/initializers ---------------------------------------------------------------------------

    /* constants */
    public static final Constants constants = new Constants();
    
    public static class Constants {
        // New values
        /** Constant value representing lookup value for interval (value = 'C1IN')*/
        public UsageRequestTypeFlagLookup INTERVAL; 
        /** Constant value representing lookup value for scalar (value = 'C1SC')*/
        public UsageRequestTypeFlagLookup SCALAR; 
        // Old Values

        public void initialize() {
            // new values
            INTERVAL = 
                LookupHelper.getLookupInstance(UsageRequestTypeFlagLookup.class, "C1IN");

            SCALAR = 
                LookupHelper.getLookupInstance(UsageRequestTypeFlagLookup.class, "C1SC");

           // original values
        }
    }

    //~ Methods ----------------------------------------------------------------------------------------------

    /* helper tester methods */
    /**
      * @return true if this Lookup represents interval
      */
    public boolean isInterval();
    /**
      * @return true if this Lookup represents scalar
      */
    public boolean isScalar();


}