/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupGen.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupGen.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;

import com.splwg.base.support.impl.AbstractComponentLookup;

/**
 * UsageRequestTypeFlagLookup_Gen is a generated implementation class for the lookup field CM_USAGE_TYPE_FLG
 *
 * @author Generated by splDev.artifactGenerator
 */
public  class UsageRequestTypeFlagLookup_Gen
    extends AbstractComponentLookup
           <UsageRequestTypeFlagLookup>
     {

    /**
      * @return field name this class represents
      */
    @Override
    public String fieldName() {
        return "CM_USAGE_TYPE_FLG             ";
    }
    /* helper tester methods */
    /**
      * @return true if this Lookup represents the lookup value interval
      */
    public boolean isInterval() {
        return getLookup().equals(UsageRequestTypeFlagLookup.constants.INTERVAL);
    }
    /**
      * @return true if this Lookup represents the lookup value scalar
      */
    public boolean isScalar() {
        return getLookup().equals(UsageRequestTypeFlagLookup.constants.SCALAR);
    }
}