/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: LookupInterface.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/LookupInterface.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.api.lookup;

import com.splwg.base.api.datatypes.Lookup;
import com.splwg.base.api.datatypes.LookupHelper;

/**
 * UsStatesLookup is a class that represents the lookup field US_STATE_FLG
 * and its values:
   <table>
     <tr> <th>FIELD_VALUE</th> <th>Property Name</th> <th>Description</th> </tr>
     <tr> <td>FM  </td> <td>micronesia</td>
             <td>Micronesia</td> </tr>
     <tr> <td>NY  </td> <td>newYork</td>
             <td>New York</td> </tr>
     <tr> <td>SD  </td> <td>southDakota</td>
             <td>South Dakota</td> </tr>
     <tr> <td>TX  </td> <td>texas</td>
             <td>Texas</td> </tr>
     <tr> <td>AZ  </td> <td>arizona</td>
             <td>Arizona</td> </tr>
     <tr> <td>NE  </td> <td>nebraska</td>
             <td>Nebraska</td> </tr>
     <tr> <td>NC  </td> <td>northCarolina</td>
             <td>North Carolina</td> </tr>
     <tr> <td>PR  </td> <td>puertoRico</td>
             <td>Puerto Rico</td> </tr>
     <tr> <td>RI  </td> <td>rhodeIsland</td>
             <td>Rhode Island</td> </tr>
     <tr> <td>NM  </td> <td>newMexico</td>
             <td>New Mexico</td> </tr>
     <tr> <td>TN  </td> <td>tennessee</td>
             <td>Tennessee</td> </tr>
     <tr> <td>KS  </td> <td>kansas</td>
             <td>Kansas</td> </tr>
     <tr> <td>IN  </td> <td>indiana</td>
             <td>Indiana</td> </tr>
     <tr> <td>MT  </td> <td>montana</td>
             <td>Montana</td> </tr>
     <tr> <td>VI  </td> <td>virginIslands</td>
             <td>Virgin Islands</td> </tr>
     <tr> <td>AL  </td> <td>alabama</td>
             <td>Alabama</td> </tr>
     <tr> <td>CO  </td> <td>colorado</td>
             <td>Colorado</td> </tr>
     <tr> <td>GU  </td> <td>guam</td>
             <td>Guam</td> </tr>
     <tr> <td>AR  </td> <td>arkansas</td>
             <td>Arkansas</td> </tr>
     <tr> <td>VA  </td> <td>virginia</td>
             <td>Virginia</td> </tr>
     <tr> <td>KY  </td> <td>kentucky</td>
             <td>Kentucky</td> </tr>
     <tr> <td>MH  </td> <td>marshallIslands</td>
             <td>Marshall Islands</td> </tr>
     <tr> <td>UT  </td> <td>utah</td>
             <td>Utah</td> </tr>
     <tr> <td>ID  </td> <td>idaho</td>
             <td>Idaho</td> </tr>
     <tr> <td>GA  </td> <td>georgia</td>
             <td>Georgia</td> </tr>
     <tr> <td>MD  </td> <td>maryland</td>
             <td>Maryland</td> </tr>
     <tr> <td>WY  </td> <td>wyoming</td>
             <td>Wyoming</td> </tr>
     <tr> <td>MP  </td> <td>marianaIslands</td>
             <td>Mariana Islands</td> </tr>
     <tr> <td>CA  </td> <td>california</td>
             <td>California</td> </tr>
     <tr> <td>IL  </td> <td>illinois</td>
             <td>Illinois</td> </tr>
     <tr> <td>MN  </td> <td>minnesota</td>
             <td>Minnesota</td> </tr>
     <tr> <td>OK  </td> <td>oklahoma</td>
             <td>Oklahoma</td> </tr>
     <tr> <td>FL  </td> <td>florida</td>
             <td>Florida</td> </tr>
     <tr> <td>NV  </td> <td>nevada</td>
             <td>Nevada</td> </tr>
     <tr> <td>PW  </td> <td>palau</td>
             <td>Palau</td> </tr>
     <tr> <td>SC  </td> <td>southCarolina</td>
             <td>South Carolina</td> </tr>
     <tr> <td>WI  </td> <td>wisconsin</td>
             <td>Wisconsin</td> </tr>
     <tr> <td>WA  </td> <td>washington</td>
             <td>Washington</td> </tr>
     <tr> <td>NH  </td> <td>newHampshire</td>
             <td>New Hampshire</td> </tr>
     <tr> <td>VT  </td> <td>vermont</td>
             <td>Vermont</td> </tr>
     <tr> <td>LA  </td> <td>louisiana</td>
             <td>Louisiana</td> </tr>
     <tr> <td>ND  </td> <td>northDakota</td>
             <td>North Dakota</td> </tr>
     <tr> <td>DC  </td> <td>washingtonDC</td>
             <td>Washington, DC</td> </tr>
     <tr> <td>HI  </td> <td>hawaii</td>
             <td>Hawaii</td> </tr>
     <tr> <td>NJ  </td> <td>newJersey</td>
             <td>New Jersey</td> </tr>
     <tr> <td>DE  </td> <td>delaware</td>
             <td>Delaware</td> </tr>
     <tr> <td>MS  </td> <td>mississippi</td>
             <td>Mississippi</td> </tr>
     <tr> <td>AK  </td> <td>alaska</td>
             <td>Alaska</td> </tr>
     <tr> <td>PA  </td> <td>pennsylvania</td>
             <td>Pennsylvania</td> </tr>
     <tr> <td>CT  </td> <td>connecticut</td>
             <td>Connecticut</td> </tr>
     <tr> <td>AS  </td> <td>americanSamoa</td>
             <td>American Samoa</td> </tr>
     <tr> <td>IA  </td> <td>iowa</td>
             <td>Iowa</td> </tr>
     <tr> <td>WV  </td> <td>westVirginia</td>
             <td>West Virginia</td> </tr>
     <tr> <td>ME  </td> <td>maine</td>
             <td>Maine</td> </tr>
     <tr> <td>OH  </td> <td>ohio</td>
             <td>Ohio</td> </tr>
     <tr> <td>MA  </td> <td>massachusetts</td>
             <td>Massachusetts</td> </tr>
     <tr> <td>MO  </td> <td>missouri</td>
             <td>Missouri</td> </tr>
     <tr> <td>OR  </td> <td>oregon</td>
             <td>Oregon</td> </tr>
     <tr> <td>MI  </td> <td>michigan</td>
             <td>Michigan</td> </tr>
    </table>
 * stored on the tables CI_LOOKUP_FIELD, CI_LOOKUP_VALUE.
 *
 * @author Generated by splDev.artifactGenerator
 */
public interface UsStatesLookup extends Lookup {

    //~ Static fields/initializers ---------------------------------------------------------------------------

    /* constants */
    public static final Constants constants = new Constants();
    
    public static class Constants {
        // New values
        /** Constant value representing lookup value for micronesia (value = 'FM  ')*/
        public UsStatesLookup MICRONESIA; 
        /** Constant value representing lookup value for newYork (value = 'NY  ')*/
        public UsStatesLookup NEW_YORK; 
        /** Constant value representing lookup value for southDakota (value = 'SD  ')*/
        public UsStatesLookup SOUTH_DAKOTA; 
        /** Constant value representing lookup value for texas (value = 'TX  ')*/
        public UsStatesLookup TEXAS; 
        /** Constant value representing lookup value for arizona (value = 'AZ  ')*/
        public UsStatesLookup ARIZONA; 
        /** Constant value representing lookup value for nebraska (value = 'NE  ')*/
        public UsStatesLookup NEBRASKA; 
        /** Constant value representing lookup value for northCarolina (value = 'NC  ')*/
        public UsStatesLookup NORTH_CAROLINA; 
        /** Constant value representing lookup value for puertoRico (value = 'PR  ')*/
        public UsStatesLookup PUERTO_RICO; 
        /** Constant value representing lookup value for rhodeIsland (value = 'RI  ')*/
        public UsStatesLookup RHODE_ISLAND; 
        /** Constant value representing lookup value for newMexico (value = 'NM  ')*/
        public UsStatesLookup NEW_MEXICO; 
        /** Constant value representing lookup value for tennessee (value = 'TN  ')*/
        public UsStatesLookup TENNESSEE; 
        /** Constant value representing lookup value for kansas (value = 'KS  ')*/
        public UsStatesLookup KANSAS; 
        /** Constant value representing lookup value for indiana (value = 'IN  ')*/
        public UsStatesLookup INDIANA; 
        /** Constant value representing lookup value for montana (value = 'MT  ')*/
        public UsStatesLookup MONTANA; 
        /** Constant value representing lookup value for virginIslands (value = 'VI  ')*/
        public UsStatesLookup VIRGIN_ISLANDS; 
        /** Constant value representing lookup value for alabama (value = 'AL  ')*/
        public UsStatesLookup ALABAMA; 
        /** Constant value representing lookup value for colorado (value = 'CO  ')*/
        public UsStatesLookup COLORADO; 
        /** Constant value representing lookup value for guam (value = 'GU  ')*/
        public UsStatesLookup GUAM; 
        /** Constant value representing lookup value for arkansas (value = 'AR  ')*/
        public UsStatesLookup ARKANSAS; 
        /** Constant value representing lookup value for virginia (value = 'VA  ')*/
        public UsStatesLookup VIRGINIA; 
        /** Constant value representing lookup value for kentucky (value = 'KY  ')*/
        public UsStatesLookup KENTUCKY; 
        /** Constant value representing lookup value for marshallIslands (value = 'MH  ')*/
        public UsStatesLookup MARSHALL_ISLANDS; 
        /** Constant value representing lookup value for utah (value = 'UT  ')*/
        public UsStatesLookup UTAH; 
        /** Constant value representing lookup value for idaho (value = 'ID  ')*/
        public UsStatesLookup IDAHO; 
        /** Constant value representing lookup value for georgia (value = 'GA  ')*/
        public UsStatesLookup GEORGIA; 
        /** Constant value representing lookup value for maryland (value = 'MD  ')*/
        public UsStatesLookup MARYLAND; 
        /** Constant value representing lookup value for wyoming (value = 'WY  ')*/
        public UsStatesLookup WYOMING; 
        /** Constant value representing lookup value for marianaIslands (value = 'MP  ')*/
        public UsStatesLookup MARIANA_ISLANDS; 
        /** Constant value representing lookup value for california (value = 'CA  ')*/
        public UsStatesLookup CALIFORNIA; 
        /** Constant value representing lookup value for illinois (value = 'IL  ')*/
        public UsStatesLookup ILLINOIS; 
        /** Constant value representing lookup value for minnesota (value = 'MN  ')*/
        public UsStatesLookup MINNESOTA; 
        /** Constant value representing lookup value for oklahoma (value = 'OK  ')*/
        public UsStatesLookup OKLAHOMA; 
        /** Constant value representing lookup value for florida (value = 'FL  ')*/
        public UsStatesLookup FLORIDA; 
        /** Constant value representing lookup value for nevada (value = 'NV  ')*/
        public UsStatesLookup NEVADA; 
        /** Constant value representing lookup value for palau (value = 'PW  ')*/
        public UsStatesLookup PALAU; 
        /** Constant value representing lookup value for southCarolina (value = 'SC  ')*/
        public UsStatesLookup SOUTH_CAROLINA; 
        /** Constant value representing lookup value for wisconsin (value = 'WI  ')*/
        public UsStatesLookup WISCONSIN; 
        /** Constant value representing lookup value for washington (value = 'WA  ')*/
        public UsStatesLookup WASHINGTON; 
        /** Constant value representing lookup value for newHampshire (value = 'NH  ')*/
        public UsStatesLookup NEW_HAMPSHIRE; 
        /** Constant value representing lookup value for vermont (value = 'VT  ')*/
        public UsStatesLookup VERMONT; 
        /** Constant value representing lookup value for louisiana (value = 'LA  ')*/
        public UsStatesLookup LOUISIANA; 
        /** Constant value representing lookup value for northDakota (value = 'ND  ')*/
        public UsStatesLookup NORTH_DAKOTA; 
        /** Constant value representing lookup value for washingtonDC (value = 'DC  ')*/
        public UsStatesLookup WASHINGTON_D_C; 
        /** Constant value representing lookup value for hawaii (value = 'HI  ')*/
        public UsStatesLookup HAWAII; 
        /** Constant value representing lookup value for newJersey (value = 'NJ  ')*/
        public UsStatesLookup NEW_JERSEY; 
        /** Constant value representing lookup value for delaware (value = 'DE  ')*/
        public UsStatesLookup DELAWARE; 
        /** Constant value representing lookup value for mississippi (value = 'MS  ')*/
        public UsStatesLookup MISSISSIPPI; 
        /** Constant value representing lookup value for alaska (value = 'AK  ')*/
        public UsStatesLookup ALASKA; 
        /** Constant value representing lookup value for pennsylvania (value = 'PA  ')*/
        public UsStatesLookup PENNSYLVANIA; 
        /** Constant value representing lookup value for connecticut (value = 'CT  ')*/
        public UsStatesLookup CONNECTICUT; 
        /** Constant value representing lookup value for americanSamoa (value = 'AS  ')*/
        public UsStatesLookup AMERICAN_SAMOA; 
        /** Constant value representing lookup value for iowa (value = 'IA  ')*/
        public UsStatesLookup IOWA; 
        /** Constant value representing lookup value for westVirginia (value = 'WV  ')*/
        public UsStatesLookup WEST_VIRGINIA; 
        /** Constant value representing lookup value for maine (value = 'ME  ')*/
        public UsStatesLookup MAINE; 
        /** Constant value representing lookup value for ohio (value = 'OH  ')*/
        public UsStatesLookup OHIO; 
        /** Constant value representing lookup value for massachusetts (value = 'MA  ')*/
        public UsStatesLookup MASSACHUSETTS; 
        /** Constant value representing lookup value for missouri (value = 'MO  ')*/
        public UsStatesLookup MISSOURI; 
        /** Constant value representing lookup value for oregon (value = 'OR  ')*/
        public UsStatesLookup OREGON; 
        /** Constant value representing lookup value for michigan (value = 'MI  ')*/
        public UsStatesLookup MICHIGAN; 
        // Old Values

        public void initialize() {
            // new values
            MICRONESIA = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "FM  ");

            NEW_YORK = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "NY  ");

            SOUTH_DAKOTA = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "SD  ");

            TEXAS = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "TX  ");

            ARIZONA = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "AZ  ");

            NEBRASKA = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "NE  ");

            NORTH_CAROLINA = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "NC  ");

            PUERTO_RICO = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "PR  ");

            RHODE_ISLAND = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "RI  ");

            NEW_MEXICO = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "NM  ");

            TENNESSEE = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "TN  ");

            KANSAS = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "KS  ");

            INDIANA = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "IN  ");

            MONTANA = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "MT  ");

            VIRGIN_ISLANDS = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "VI  ");

            ALABAMA = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "AL  ");

            COLORADO = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "CO  ");

            GUAM = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "GU  ");

            ARKANSAS = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "AR  ");

            VIRGINIA = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "VA  ");

            KENTUCKY = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "KY  ");

            MARSHALL_ISLANDS = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "MH  ");

            UTAH = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "UT  ");

            IDAHO = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "ID  ");

            GEORGIA = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "GA  ");

            MARYLAND = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "MD  ");

            WYOMING = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "WY  ");

            MARIANA_ISLANDS = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "MP  ");

            CALIFORNIA = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "CA  ");

            ILLINOIS = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "IL  ");

            MINNESOTA = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "MN  ");

            OKLAHOMA = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "OK  ");

            FLORIDA = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "FL  ");

            NEVADA = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "NV  ");

            PALAU = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "PW  ");

            SOUTH_CAROLINA = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "SC  ");

            WISCONSIN = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "WI  ");

            WASHINGTON = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "WA  ");

            NEW_HAMPSHIRE = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "NH  ");

            VERMONT = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "VT  ");

            LOUISIANA = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "LA  ");

            NORTH_DAKOTA = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "ND  ");

            WASHINGTON_D_C = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "DC  ");

            HAWAII = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "HI  ");

            NEW_JERSEY = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "NJ  ");

            DELAWARE = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "DE  ");

            MISSISSIPPI = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "MS  ");

            ALASKA = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "AK  ");

            PENNSYLVANIA = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "PA  ");

            CONNECTICUT = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "CT  ");

            AMERICAN_SAMOA = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "AS  ");

            IOWA = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "IA  ");

            WEST_VIRGINIA = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "WV  ");

            MAINE = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "ME  ");

            OHIO = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "OH  ");

            MASSACHUSETTS = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "MA  ");

            MISSOURI = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "MO  ");

            OREGON = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "OR  ");

            MICHIGAN = 
                LookupHelper.getLookupInstance(UsStatesLookup.class, "MI  ");

           // original values
        }
    }

    //~ Methods ----------------------------------------------------------------------------------------------

    /* helper tester methods */
    /**
      * @return true if this Lookup represents micronesia
      */
    public boolean isMicronesia();
    /**
      * @return true if this Lookup represents newYork
      */
    public boolean isNewYork();
    /**
      * @return true if this Lookup represents southDakota
      */
    public boolean isSouthDakota();
    /**
      * @return true if this Lookup represents texas
      */
    public boolean isTexas();
    /**
      * @return true if this Lookup represents arizona
      */
    public boolean isArizona();
    /**
      * @return true if this Lookup represents nebraska
      */
    public boolean isNebraska();
    /**
      * @return true if this Lookup represents northCarolina
      */
    public boolean isNorthCarolina();
    /**
      * @return true if this Lookup represents puertoRico
      */
    public boolean isPuertoRico();
    /**
      * @return true if this Lookup represents rhodeIsland
      */
    public boolean isRhodeIsland();
    /**
      * @return true if this Lookup represents newMexico
      */
    public boolean isNewMexico();
    /**
      * @return true if this Lookup represents tennessee
      */
    public boolean isTennessee();
    /**
      * @return true if this Lookup represents kansas
      */
    public boolean isKansas();
    /**
      * @return true if this Lookup represents indiana
      */
    public boolean isIndiana();
    /**
      * @return true if this Lookup represents montana
      */
    public boolean isMontana();
    /**
      * @return true if this Lookup represents virginIslands
      */
    public boolean isVirginIslands();
    /**
      * @return true if this Lookup represents alabama
      */
    public boolean isAlabama();
    /**
      * @return true if this Lookup represents colorado
      */
    public boolean isColorado();
    /**
      * @return true if this Lookup represents guam
      */
    public boolean isGuam();
    /**
      * @return true if this Lookup represents arkansas
      */
    public boolean isArkansas();
    /**
      * @return true if this Lookup represents virginia
      */
    public boolean isVirginia();
    /**
      * @return true if this Lookup represents kentucky
      */
    public boolean isKentucky();
    /**
      * @return true if this Lookup represents marshallIslands
      */
    public boolean isMarshallIslands();
    /**
      * @return true if this Lookup represents utah
      */
    public boolean isUtah();
    /**
      * @return true if this Lookup represents idaho
      */
    public boolean isIdaho();
    /**
      * @return true if this Lookup represents georgia
      */
    public boolean isGeorgia();
    /**
      * @return true if this Lookup represents maryland
      */
    public boolean isMaryland();
    /**
      * @return true if this Lookup represents wyoming
      */
    public boolean isWyoming();
    /**
      * @return true if this Lookup represents marianaIslands
      */
    public boolean isMarianaIslands();
    /**
      * @return true if this Lookup represents california
      */
    public boolean isCalifornia();
    /**
      * @return true if this Lookup represents illinois
      */
    public boolean isIllinois();
    /**
      * @return true if this Lookup represents minnesota
      */
    public boolean isMinnesota();
    /**
      * @return true if this Lookup represents oklahoma
      */
    public boolean isOklahoma();
    /**
      * @return true if this Lookup represents florida
      */
    public boolean isFlorida();
    /**
      * @return true if this Lookup represents nevada
      */
    public boolean isNevada();
    /**
      * @return true if this Lookup represents palau
      */
    public boolean isPalau();
    /**
      * @return true if this Lookup represents southCarolina
      */
    public boolean isSouthCarolina();
    /**
      * @return true if this Lookup represents wisconsin
      */
    public boolean isWisconsin();
    /**
      * @return true if this Lookup represents washington
      */
    public boolean isWashington();
    /**
      * @return true if this Lookup represents newHampshire
      */
    public boolean isNewHampshire();
    /**
      * @return true if this Lookup represents vermont
      */
    public boolean isVermont();
    /**
      * @return true if this Lookup represents louisiana
      */
    public boolean isLouisiana();
    /**
      * @return true if this Lookup represents northDakota
      */
    public boolean isNorthDakota();
    /**
      * @return true if this Lookup represents washingtonDC
      */
    public boolean isWashingtonDC();
    /**
      * @return true if this Lookup represents hawaii
      */
    public boolean isHawaii();
    /**
      * @return true if this Lookup represents newJersey
      */
    public boolean isNewJersey();
    /**
      * @return true if this Lookup represents delaware
      */
    public boolean isDelaware();
    /**
      * @return true if this Lookup represents mississippi
      */
    public boolean isMississippi();
    /**
      * @return true if this Lookup represents alaska
      */
    public boolean isAlaska();
    /**
      * @return true if this Lookup represents pennsylvania
      */
    public boolean isPennsylvania();
    /**
      * @return true if this Lookup represents connecticut
      */
    public boolean isConnecticut();
    /**
      * @return true if this Lookup represents americanSamoa
      */
    public boolean isAmericanSamoa();
    /**
      * @return true if this Lookup represents iowa
      */
    public boolean isIowa();
    /**
      * @return true if this Lookup represents westVirginia
      */
    public boolean isWestVirginia();
    /**
      * @return true if this Lookup represents maine
      */
    public boolean isMaine();
    /**
      * @return true if this Lookup represents ohio
      */
    public boolean isOhio();
    /**
      * @return true if this Lookup represents massachusetts
      */
    public boolean isMassachusetts();
    /**
      * @return true if this Lookup represents missouri
      */
    public boolean isMissouri();
    /**
      * @return true if this Lookup represents oregon
      */
    public boolean isOregon();
    /**
      * @return true if this Lookup represents michigan
      */
    public boolean isMichigan();


}