/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: ComponentInterface.VM
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/ComponentInterface.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.domain.toDo.toDoType;

import com.splwg.base.api.BusinessComponent;
import com.splwg.base.domain.todo.toDoType.ToDoTypeToDoPostProcessAlgorithmSpot; 

/**
  * Interface for the cmpToDoPostProcessingAdjustmentFreezeAlg component
  *
  * @author Generated by com.splwg.tools.artifactgen.ArtifactGenerator
  */
public interface CmpToDoPostProcessingAdjustmentFreezeAlg extends BusinessComponent
                 , ToDoTypeToDoPostProcessAlgorithmSpot 
                  {


    /**
      * 
      */
     
     void setNewToDoEntry(com.splwg.base.domain.todo.toDoEntry.ToDoEntry toDoEntry) ;

    /**
      * 
      */
     
     void setOldToDoEntryDTO(com.splwg.base.domain.todo.toDoEntry.ToDoEntry_DTO toDoEntryDTO) ;

    /**
      * 
      */
     
     void invoke() ;

}
